var Balloon=function(a,b){this._id=a;this._params=b;this._obj=$("#"+a);this.init()};
Balloon.prototype={init:function(){var a=this._params;this._text=this._obj.html();this._obj.empty();this._bg=$('<div class="bg"></div>').appendTo(this._obj);this._fg=$('<div class="fg">'+htmlToView(this._text)+"</div>").css({padding:a.margin+"px","text-align":a.txt_a_0}).appendTo(this._obj);applyFontParameters(0,"",this._fg,a);initReferences(this);var b=this;setTimeout(function(){updateElementAndReferences(b)},0)},updateUI:function(a){var b=this._params,d=a.children(".bg"),c=a.children(".fg"),e=a.width(),
a=a.height(),f=b.bdr_tl_0,g=b.bdr_tr_0,i=b.bdr_br_0,l=b.bdr_bl_0;canvas=createCanvas(e,a);d.empty().append(canvas);d=canvas.getContext("2d");d.beginPath();var j=b.bdw_0,m=b.bdsw_int_0,k=b.bdsw_amp_0;switch(b.dir){case 0:var n=e-f-g,o=a*b.tipLength,q=n*b.rootWidth,p=n*b.rootOffset;p+q>n&&(p=n-q);n*=b.tipOffset;c.css({top:o+"px",width:e-2*b.margin+"px",height:a-o+"px"});var h={x:j+f,y:j+o},c={x:j+f+p,y:h.y};drawSwingLine(d,h,c,m,k,!1);h=c;c={x:n,y:j};drawSwingLine(d,h,c,m,k,!0);h=c;c={x:j+f+p+q,y:j+
o};drawSwingLine(d,h,c,m,k,!0);h=c;c={x:e-j-g,y:h.y};drawSwingLine(d,h,c,m,k,!0);h=c.x;c=c.y+g;d.arc(h,c,g,1.5*Math.PI,0,!1);h={x:h+g,y:c};c={x:e-j,y:a-j-i};drawSwingLine(d,h,c,m,k,!0);h=c.x-i;c=c.y;d.arc(h,c,i,0,0.5*Math.PI,!1);h={x:h,y:c+i};c={x:j+l,y:h.y};drawSwingLine(d,h,c,m,k,!0);h=c.x;c=c.y-l;d.arc(h,c,l,0.5*Math.PI,Math.PI,!1);h={x:h-l,y:c};c={x:h.x,y:j+o+f};drawSwingLine(d,h,c,m,k,!0);h=c.x+f;c=c.y;d.arc(h,c,f,Math.PI,1.5*Math.PI,!1);break;case 1:n=a-f-l;o=e*b.tipLength;q=n*b.rootWidth;p=
n*b.rootOffset;p+q>n&&(p=n-q);n*=b.tipOffset;c.css({left:o+"px",width:e-o-2*b.margin+"px",height:a+"px"});h={x:j+o+f,y:j};c={x:e-j-g,y:h.y};drawSwingLine(d,h,c,m,k,!1);h=c.x;c=c.y+g;d.arc(h,c,g,1.5*Math.PI,0,!1);h={x:h+g,y:c};c={x:e-j,y:a-j-i};drawSwingLine(d,h,c,m,k,!0);h=c.x-i;c=c.y;d.arc(h,c,i,0,0.5*Math.PI,!1);h={x:h,y:c+i};c={x:j+o+l,y:h.y};drawSwingLine(d,h,c,m,k,!0);h=c.x;c=c.y-l;d.arc(h,c,l,0.5*Math.PI,Math.PI,!1);h={x:h-l,y:c};c={x:h.x,y:j+f+p+q};drawSwingLine(d,h,c,m,k,!0);h=c;c={x:j,y:n};
drawSwingLine(d,h,c,m,k,!0);h=c;c={x:j+o,y:j+f+p};drawSwingLine(d,h,c,m,k,!0);h=c;c={x:h.x,y:j+f};drawSwingLine(d,h,c,m,k,!0);h=c.x+f;c=c.y;d.arc(h,c,f,Math.PI,1.5*Math.PI,!1);break;case 2:n=e-l-i;o=a*b.tipLength;q=n*b.rootWidth;p=n*b.rootOffset;p+q>n&&(p=n-q);n*=b.tipOffset;c.css({width:e-2*b.margin+"px",height:a-o+"px"});h={x:j+f,y:j};c={x:e-j-g,y:h.y};drawSwingLine(d,h,c,m,k,!1);h=c.x;c=c.y+g;d.arc(h,c,g,1.5*Math.PI,0,!1);h={x:h+g,y:c};c={x:e-j,y:a-j-o-i};drawSwingLine(d,h,c,m,k,!0);h=c.x-i;c=
c.y;d.arc(h,c,i,0,0.5*Math.PI,!1);h={x:h,y:c+i};c={x:j+l+p+q,y:h.y};drawSwingLine(d,h,c,m,k,!0);h=c;c={x:n,y:a-j};drawSwingLine(d,h,c,m,k,!0);h=c;c={x:j+l+p,y:a-j-o};drawSwingLine(d,h,c,m,k,!0);h=c;c={x:j+l,y:h.y};drawSwingLine(d,h,c,m,k,!0);h=c.x;c=c.y-l;d.arc(h,c,l,0.5*Math.PI,Math.PI,!1);h={x:h-l,y:c};c={x:h.x,y:j+f};drawSwingLine(d,h,c,m,k,!0);h=c.x+f;c=c.y;d.arc(h,c,f,Math.PI,1.5*Math.PI,!1);break;case 3:n=a-g-i,o=e*b.tipLength,q=n*b.rootWidth,p=n*b.rootOffset,p+q>n&&(p=n-q),n*=b.tipOffset,c.css({width:e-
o-2*b.margin+"px",height:a+"px"}),h={x:j+f,y:j},c={x:e-j-o-g,y:h.y},drawSwingLine(d,h,c,m,k,!1),h=c.x,c=c.y+g,d.arc(h,c,g,1.5*Math.PI,0,!1),h={x:h+g,y:c},c={x:h.x,y:j+g+p},drawSwingLine(d,h,c,m,k,!0),h=c,c={x:e-j,y:n},drawSwingLine(d,h,c,m,k,!0),h=c,c={x:e-j-o,y:j+p+q},drawSwingLine(d,h,c,m,k,!0),h=c,c={x:h.x,y:a-j-i},drawSwingLine(d,h,c,m,k,!0),h=c.x-i,c=c.y,d.arc(h,c,i,0,0.5*Math.PI,!1),h={x:h,y:c+i},c={x:j+l,y:h.y},drawSwingLine(d,h,c,m,k,!0),h=c.x,c=c.y-l,d.arc(h,c,l,0.5*Math.PI,Math.PI,!1),h=
{x:h-l,y:c},c={x:h.x,y:j+f},drawSwingLine(d,h,c,m,k,!0),h=c.x+f,c=c.y,d.arc(h,c,f,Math.PI,1.5*Math.PI,!1)}d.closePath();fillAndStrokeOnCanvas(d,e,a,b)}};window.foreui||(window.foreui={});window.foreui.behaviors={};var Button=function(a,b){this._id=a;this._params=b;this._obj=$("#"+a);this.init()};
Button.prototype={init:function(){var a=this._params;this._text=this._obj.html();this._obj.empty();this._bg=$('<div class="bg"></div>').appendTo(this._obj);this._bd=$('<div class="bd"></div>').appendTo(this._obj);a=createLabelObject(a.icon,a.icon_p,a.gap,this._text);this._fg=$('<table class="fg" cellspacing="0" cellpadding="0"><tr><td class="labelWrapper" style="white-space:nowrap">'+a.html()+"</td></tr></table>").appendTo(this._obj);this._fg.add(this._fg.find("tr")).add(this._fg.find("td")).css("background-image",
"url('styles/empty.gif')");this.setupBehavior(this._obj);initReferences(this);var b=this;setTimeout(function(){setState(b,b._params.state,!0)},0)},updateUI:function(a){var b=this._params,d=b.state,c=a.children(".bg"),e=a.children(".bd"),f=a.children(".fg"),g=a.width(),a=a.height();e.css("border-width","0px").width(g).height(a);generateBackgroundAndBorders(d,"",c,e,b);c=f.find(".labelWrapper").contents().filter(function(){return 3==this.nodeType});e=""==this._text?" ":this._text;$("<div>").text(c.text()).html()!=
e&&c.replaceWith(e);e=getTextSize(this._text,b["f_n_"+d],b["f_s_"+d]).width;e=2>b.icon_p?e+(b.icon?f.find(".icon").width()+b.gap:0):Math.max(e,f.find(".icon").width());c=b["txt_a_"+d];e=Math.min(b.margin,(g-e)/2-b["bdw_"+d]);f.width(g).height(a).css({"text-align":c,"padding-left":e,"padding-right":e,cursor:64==d||96==d?"default":"pointer"});applyFontParameters(d,"",f.find("td"),b)},setupBehavior:function(a){var b=this;a.mouseenter(function(){setState(b,16)}).mouseleave(function(){setState(b,0)}).mousedown(function(){setState(b,
32)}).mouseup(function(){setState(b,0)})},setText:function(a){this._text=a}};var getPostfixForState=function(a){return 0==a?"__Normal":16==a?"__Hovering":32==a?"__Selected":64==a?"__Disabled":48==a?"__Selected_Hovering":96==a?"__Selected_Disabled":""},createCanvas=function(a,b){if("undefined"==typeof G_vmlCanvasManager)return $('<canvas width="'+a+'" height="'+b+'"></canvas>').get(0);var d=document.createElement("canvas");d.setAttribute("width",a);d.setAttribute("height",b);G_vmlCanvasManager.initElement(d);return d},drawSwingLine=function(a,b,d,c,e,f,g){f?a.lineTo(b.x,b.y):
a.moveTo(b.x,b.y);var i=Math.round(Math.sqrt(Math.pow(b.x-d.x,2)+Math.pow(b.y-d.y,2)));if(0<c&&0<e&&0<i){for(var f=Math.floor(e/2),l=(d.x-b.x)/i,j=(d.y-b.y)/i,m=0,k=0,i=Math.floor(i/c),m=0,n=1,o=[0,1],q=2;q<i;q++)o[q]=o[q-1]+o[q-2];for(q=1;q<i;q++)m=q*o[q-1]%o[q]%e-f,k=o[q-1]%e-f,n=Math.abs(k-n)>f?1:k,k=q*c,m=b.x+Math.round(l*k)+m,k=b.y+Math.round(j*k)+n,a.lineTo(m,k)}a.lineTo(d.x,d.y);g&&a.stroke()},drawSwingBorder=function(a,b,d,c,e,f,g,i,l,j,m,k,n,o,q){var p=f/2,h=g/2,u=i/2,t=l/2,s=Math.min(c-
t-h,e-p-u)/2,j=Math.min(j,s),m=Math.min(m,s),k=Math.min(k,s),n=Math.min(n,s),s=p+j,v=p+m,w=h+k,x=u+k,z=t+n,A=u+n,r=b+(t+j),p=d+p,y=b+c-(t+m)-1;0<f&&(a.lineWidth=f,a.beginPath(),drawSwingLine(a,{x:r,y:p},{x:y,y:p},o,q,!1,!0));r=y;if(0<m&&(0<f||0<g))a.arc(r,p+m,m,1.5*Math.PI,2*Math.PI,!1),a.stroke();r=b+c-h-1;p=d+v;nextY=d+e-x-1;0<g&&(a.lineWidth=g,a.beginPath(),drawSwingLine(a,{x:r,y:p},{x:r,y:nextY},o,q,!1,!0));p=nextY;if(0<k&&(0<i||0<g))a.arc(r-k,p,k,0,0.5*Math.PI,!1),a.stroke();r=b+c-1-w;p=d+e-
u-1;y=b+z;0<i&&(a.lineWidth=i,a.beginPath(),drawSwingLine(a,{x:r,y:p},{x:y,y:p},o,q,!1,!0));r=y;if(0<n&&(0<i||0<l))a.arc(r,p-n,n,0.5*Math.PI,Math.PI,!1),a.stroke();r=b+t;p=d+e-1-A;nextY=d+s;0<l&&(a.lineWidth=l,a.beginPath(),drawSwingLine(a,{x:r,y:p},{x:r,y:nextY},o,q,!1,!0));p=nextY;if(0<j&&(0<f||0<l))a.arc(r+j,p,j,Math.PI,1.5*Math.PI,!1),a.stroke()},fillAndStrokeOnCanvas=function(a,b,d,c,e,f){if(!e){if(c["bg_"+c.state].colors){for(var e=c["bg_"+c.state],g=e.bkRegion,b=a.createLinearGradient(e.startX*
b/g.width,e.startY*d/g.height,e.endX*b/g.width,e.endY*d/g.height),d=e.fractions,e=e.colors,g=0;g<d.length;g++)b.addColorStop(d[g],e[g]);a.fillStyle=b}else a.fillStyle=c["bg_"+c.state];a.save();void 0!==c.bgo&&(a.globalAlpha=c.bgo);a.fill();a.restore()}!f&&c["bd_paint_"+c.state]&&(a.lineWidth=c["bdw_"+c.state],a.strokeStyle=c["bdc_"+c.state],a.stroke())},drawEllipse=function(a,b,d,c,e,f,g){var i=0.5522848*(c/2),l=0.5522848*(e/2),j=b+c,m=d+e,c=b+c/2,e=d+e/2;a.beginPath();a.moveTo(b,e);a.bezierCurveTo(b,
e-l,c-i,d,c,d);a.bezierCurveTo(c+i,d,j,e-l,j,e);a.bezierCurveTo(j,e+l,c+i,m,c,m);a.bezierCurveTo(c-i,m,b,e+l,b,e);a.closePath();g&&(a.lineWidth=f["bdw_"+f.state],a.strokeStyle=f["bdc_"+f.state],a.stroke())},getTextSize=function(a,b,d,c){var e=!1;if(!a||""==a)e=!0,a="H";a=$('<span style="position:absolute; z-index:-1">'+a+"</span>").appendTo("body");b&&a.css("font-family",b);d&&a.css("font-size",d);c&&a.css("font-weight","bold");b=a.get(0);e=e?0:b.clientWidth;b=b.clientHeight;a.remove();return{width:e,
height:b}},getScrollBarSize=function(){var a=$('<p style="width:100%;height:200px;"></p>'),b=$('<div style="position:absolute;top:0px;left:0px;visibility:hidden;width:200px;height:150px;overflow:hidden"></div>').append(a).appendTo("body"),d=a.get(0).offsetWidth;b.css("overflow","scroll");a=a.get(0).offsetWidth;d==a&&(a=b.get(0).clientWidth);b.remove();return d-a},rotateRectangle=function(a){var b=a.x;a.x=a.y;a.y=b;b=a.width;a.width=a.height;a.height=b},changeBackground=function(a,b,d,c,e,f,g){e||
(e=c[b+"bg_"+a]);if(0==e.indexOf("#")||"transparent"==e||0==e.indexOf("rgba("))d.css("background-color",e);else{var f=f?f:d.innerWidth(),g=g?g:d.innerHeight(),e=$('<img class="linearBg" src="images/'+e+'" width="'+f+'" height="'+g+'" align="top" />'),g=c[b+"bdr_tl_"+a],f=c[b+"bdr_tr_"+a],i=c[b+"bdr_br_"+a],a=c[b+"bdr_bl_"+a];e.css({"-moz-border-radius-topleft":g+"px","-webkit-border-top-left-radius":g+"px","border-top-left-radius":g+"px","-moz-border-radius-topright":f+"px","-webkit-border-top-right-radius":f+
"px","border-top-right-radius":f+"px","-moz-border-radius-bottomleft":a+"px","-webkit-border-bottom-left-radius":a+"px","border-bottom-left-radius":a+"px","-moz-border-radius-bottomright":i+"px","-webkit-border-bottom-right-radius":i+"px","border-bottom-right-radius":i+"px"});d.children(".linearBg").remove();d.prepend(e)}},changeBorders=function(a,b,d,c,e){var f=c[b+"bdt_"+a],g=c[b+"bdc_"+a],i=c[b+"bd_t_"+a],l=c[b+"bd_r_"+a],j=c[b+"bd_b_"+a],m=c[b+"bd_l_"+a],k=c[b+"bdr_tl_"+a],n=c[b+"bdr_tr_"+a],
o=c[b+"bdr_br_"+a],q=c[b+"bdr_bl_"+a],p=c[b+"bdsw_int_"+a],a=c[b+"bdsw_amp_"+a];"swing"==f?(e=d.outerWidth(),f=d.outerHeight(),b=Math.floor(a/2),c=createCanvas(e,f),c.style.position="absolute",c.className="swingBd",d.children(".swingBd").remove(),d.prepend(c),d=c.getContext("2d"),d.strokeStyle=g,drawSwingBorder(d,b,b,e-2*b,f-2*b,i,l,j,m,k,n,o,q,p,a)):"none"!=f&&(d.css({"border-style":f,"border-color":g,"border-top-width":i+"px","border-left-width":m+"px","border-bottom-width":j+"px","border-right-width":l+
"px"}),e&&d.css({"-moz-border-radius-topleft":k+"px","-webkit-border-top-left-radius":k+"px","border-top-left-radius":k+"px","-moz-border-radius-topright":n+"px","-webkit-border-top-right-radius":n+"px","border-top-right-radius":n+"px","-moz-border-radius-bottomleft":q+"px","-webkit-border-bottom-left-radius":q+"px","border-bottom-left-radius":q+"px","-moz-border-radius-bottomright":o+"px","-webkit-border-bottom-right-radius":o+"px","border-bottom-right-radius":o+"px"}))},generateBackgroundAndBorders=
function(a,b,d,c,e){var f=d.outerWidth(),g=d.outerHeight(),i=c.outerWidth(),l=c.outerHeight(),j=""!=b||!e.bg?e[b+"bg_"+a]:e.bg,m=e[b+"bgo_"+a],k=e[b+"shd_"+a],n=e[b+"bd_paint_"+a],o=e[b+"bdt_"+a],q=e[b+"bdc_"+a],p=e[b+"bd_t_"+a],h=e[b+"bd_r_"+a],u=e[b+"bd_b_"+a],t=e[b+"bd_l_"+a],s=e[b+"bdr_tl_"+a],v=e[b+"bdr_tr_"+a],w=e[b+"bdr_br_"+a],x=e[b+"bdr_bl_"+a],z=e[b+"bdsw_int_"+a],a=e[b+"bdsw_amp_"+a];d.children(".linearBg").remove();0==j.indexOf("#")||"transparent"==j||0==j.indexOf("rgba(")?d.css("background-color",
j):d.prepend($('<img class="linearBg" src="images/'+j+'" width="'+(d==c?f-t-h:f)+'" height="'+(d==c?g-p-u:g)+'" align="top" />'));void 0!=m&&d.fadeTo(0,m/255);k&&d.css({"box-shadow":k,"-moz-box-shadow":k,"-webkit-box-shadow":k});f={"-moz-border-radius-topleft":s+"px","-webkit-border-top-left-radius":s+"px","border-top-left-radius":s+"px","-moz-border-radius-topright":v+"px","-webkit-border-top-right-radius":v+"px","border-top-right-radius":v+"px","-moz-border-radius-bottomleft":x+"px","-webkit-border-bottom-left-radius":x+
"px","border-bottom-left-radius":x+"px","-moz-border-radius-bottomright":w+"px","-webkit-border-bottom-right-radius":w+"px","border-bottom-right-radius":w+"px"};n&&("swing"==o?(n=Math.floor(a/2),o=createCanvas(i,l),o.style.position="absolute",o.className="swingBd",c.children(".swingBd").remove(),g=c.children(":first"),0<g.length&&g.hasClass("labelBg")?g.after(o):c.prepend(o),c=o.getContext("2d"),c.strokeStyle=q,drawSwingBorder(c,n,n,i-2*n,l-2*n,p,h,u,t,s,v,w,x,z,a)):"none"!=o&&(q={"border-style":o,
"border-color":q,"border-top-width":p+"px","border-left-width":t+"px","border-bottom-width":u+"px","border-right-width":h+"px"},c.css({width:i-t-h+"px",height:l-p-u+"px"}).css(q).css(f)));d.css(f).find("img").css(f)},applyFontParameters=function(a,b,d,c){d.css({"font-family":c[b+"f_n_"+a],"font-size":c[b+"f_s_"+a],color:c[b+"f_c_"+a],"font-weight":c[b+"f_b_"+a]?"bold":"normal","font-style":c[b+"f_i_"+a]?"italic":"normal","text-decoration":c[b+"f_u_"+a]?"underline":"none"})},createLabelObject=function(a,
b,d,c,e){var f=$('<span class="label" style="white-space:nowrap;"></span>');a?(a='<img class="icon" src='+(e?'"images/':'"images/dock/')+a+'" align="absmiddle" />',f.html((0==b%2?a:c)+(1<b?'<div style="font-size:1px; width:'+d+"px; height:"+d+'px"/>':'<span style="display:inline-block; width:'+d+"px; height:"+d+'px"/>')+(0==b%2?c:a))):f.html(c);return f},initReferences=function(a){var b=a._params;b.tooltip&&a._obj.attr("title",b.tooltip);var d=a._obj.first();$('[ref="'+a._id+'"]').each(function(){var c=
$(this);!c.attr("title")&&b.tooltip&&c.attr("title",b.tooltip);getForeUIElementById(c.attr("id"));c.empty().append(d.clone(!1).children());c.find(".elem").each(function(){var a=$(this),b=a.attr("id");a.attr("id",c.attr("id")+"__"+b).attr("ref",b)});a.setupBehavior&&a.setupBehavior(c);a.updateUI(c)})},updateElementAndReferences=function(a){a.updateUI(a._obj);$('[ref="'+a._id+'"]').each(function(){a.updateUI($(this))})},isPage=function(a){return null!=a&&null!=a.id&&0==a.id.indexOf("Page_")},getPageByObject=
function(a){for(;a=a.parentNode;)if(isPage(a))return a;return null},canACoverB=function(a,b){if(null==a)return!1;if(null==b)return!0;this.getActualZ=function(a){try{var b="auto"==a.style.zIndex?0:a.style.zIndex}catch(c){b=0}"number"!=typeof b&&(b=parseInt(b,10));return b};this.getChildIndex=function(a,b){for(var c=0;c<b.parentNode.childNodes.length;c++)if(b.parentNode.childNodes[c]==b)return c};var d=isPage(a.parentNode)?a:a.parentNode,c=isPage(b.parentNode)?b:b.parentNode,e=isPage(d.parentNode)?
d:d.parentNode,f=isPage(c.parentNode)?c:c.parentNode;if(e!=f&&(e!=d||f!=c))return canACoverB(e,f);e=this.getActualZ(d);f=this.getActualZ(c);e==f&&d.parentNode==c.parentNode&&(e=this.getChildIndex(d.parentNode,d),f=this.getChildIndex(c.parentNode,c));return e>=f},rectInRect=function(a,b,d,c,e,f,g,i){this.ptInRect=function(a,b,c,d,e,f){return a>=c&&a<c+e&&b>=d&&b<d+f};var l=this.ptInRect(a,b,e,f,g,i),j=this.ptInRect(a,b+c-1,e,f,g,i),m=this.ptInRect(a+d-1,b,e,f,g,i),a=this.ptInRect(a+d-1,b+c-1,e,f,g,
i);return l&&j&&m&&a},objectsInRect=function(a,b,d,c,e,f){f||(f=a);var g=[];$(".elem",a).each(function(){if(canACoverB(this,f)){var a=getBounds(this);rectInRect(a.x,a.y,a.w,a.h,b,d,c,e)&&g.push(this)}});return g},initBehaviorForId=function(a){a=window.foreui.behaviors[a];if(void 0!=a)for(var b=0;b<a.length;b++)void 0==a[b].executed&&canExecuteBehavior(a[b])&&(a[b].instance.callMe(),a[b].executed=!0)},canExecuteBehavior=function(a){void 0==a.instance&&(a.instance=new a);var a=a.instance.selector,b=
a.size();if(0<b){for(var d=0;d<b;d++){var c=a.eq(d).attr("id");if(0==c.indexOf("Page_"))break;if(0!=c.indexOf("Reference_")&&!window.foreui.elements[c])return!1}return!0}return!1},initDefaultBehaviorForElement=function(a){a&&a._obj.bind("mouseenter mouseleave mousemove mouseover mouseout mousedown mouseup contextmenu click Selection_Changed Value_Changed",function(b){a&&0<(a._params.state&64)&&b.stopImmediatePropagation()}).mousedown(function(a){$(a.target).parentsUntil(".elem").parent().attr("id")==
this.id&&(window.foreui.focusedElementId=this.id,onPropertyValueChanged("FOCUSED_ELEMENT_ID",this.id))})},getForeUIElementById=function(a){if(!window.foreui.elements[a]){var b=window.foreui.elements.constructors[a];b&&(b(),0==a.indexOf("Table_")&&(changeVisibility([a],-1,!1),changeVisibility([a],-1,!1)),initDefaultBehaviorForElement(window.foreui.elements[a]),initBehaviorForId(a),window.foreui.elements[a]._obj.trigger("Initialized"))}return window.foreui.elements[a]},getBoundsById=function(a){return getBounds(document.getElementById(a))},
getBounds=function(a){for(var b=$(a),b={x:a.offsetLeft,y:a.offsetTop,w:b.outerWidth(),h:b.outerHeight()},d=a.offsetLeft,c=a.offsetTop;(a=a.offsetParent)&&!isPage(a);)b.x+=a.offsetLeft,b.y+=a.offsetTop;b.parentX=b.x-d;b.parentY=b.y-c;return b},getBoundsByIds=function(a,b){for(var d,c,e,f,g=0;g<a.length;g++){b[g]=getBoundsById(a[g]);if(void 0==d||b[g].x<d)d=b[g].x;if(void 0==c||b[g].y<c)c=b[g].y;if(void 0==e||b[g].x+b[g].w-1>e)e=b[g].x+b[g].w-1;if(void 0==f||b[g].y+b[g].h-1>f)f=b[g].y+b[g].h-1}return{x:d,
y:c,w:e-d+1,h:f-c+1}},isDescendantOf=function(a,b){var d=$("#"+a),c=$("#"+b);return 0<d.size()&&0<c.size()?0<=d.parents().index(c):!1},isDescendantOfAny=function(a,b){for(var d=0;d<b.length;d++)if(isDescendantOf(a,b[d]))return!0;return!1},isEmbeddedElement=function(a){return 0<$("#"+a).parents(".elem").size()},appendInnerObjects=function(a,b){if(0<b.length){var d=getPageByObject(document.getElementById(b[0])),c=b.slice();c.sort(function(a,b){return a==b?0:canACoverB(document.getElementById(a),document.getElementById(b))?
1:-1});c=document.getElementById(c[0]);d=objectsInRect(d,a.x,a.y,a.w,a.h,c);for(c=0;c<d.length;c++)!isEmbeddedElement(d[c].id)&&(-1==$.inArray(d[c].id,b)&&!isDescendantOfAny(d[c].id,b))&&b.push(d[c].id)}},supportState=function(a,b){return-1!=$.inArray(b,a._params.states)},setState=function(a,b,d){if(supportState(a,b)&&(d||a._params.state!=b&&0==(a._params.state&64))){var d=a._params.state&32,c=b&32;a._params.state=b;if(a.onStateChanged)a.onStateChanged();if(a.onSelected&&!d&&c)a.onSelected();if(a.onUnselected&&
d&&!c)a.onUnselected();updateElementAndReferences(a)}},getEvent=function(){if(document.all)return window.event;for(func=getEvent.caller;null!=func;){var a=func.arguments[0];if(a&&(a.constructor==Event||a.constructor==MouseEvent||"object"==typeof a&&a.preventDefault&&a.stopPropagation))return a;func=func.caller}return null},getPropertyValue=function(a){var b=a.indexOf(".");if(-1!=b){var d=a.substring(0,b),a=a.substring(b+1,a.length);return getElementPropertyValue(d,a)}d=window.foreui.sys_properties[a];
if(void 0!=d)return d.call();a=window.foreui.properties[a];return null!=a?a.value:null},isPageExcluded=function(a){return"true"==$("#Page_"+a).attr("excluded")},getElementTypeById=function(a){var b=a.indexOf("_");return-1==b?"Unknown":a.substring(0,b)},findSiblingsInGroup=function(a,b){for(var d=[],c=0;c<a.length;c++){var e=getForeUIElementById(a[c]);if(e){b&&-1==$.inArray(a[c],d)&&d.push(a[c]);var f=getElementTypeById(a[c]),g=e._obj.parent();g.hasClass("elem")&&0==g.attr("id").indexOf("Group")&&
e._obj.siblings(".elem").filter(function(){return this.id&&0==this.id.indexOf(f)}).each(function(){-1==$.inArray(this.id,d)&&$.inArray(this.id,a)&&d.push(this.id)})}}return d},htmlToView=function(a){a=(""+a).replace(/\n/gi,"<br>");a=a.replace(/([^\s])\s/gi,"$1&escsp;");a=a.replace(/\s/gi,"&nbsp;");return a=a.replace(/&escsp;/gi," ")},textFromView=function(a){a=(""+a).replace(/<br>/gi,"\n");return a=a.replace(/&nbsp;/gi," ")},
toJsonString=function(a){$.isArray(a)?a=oneBasedToZeroBased($.extend(!0,[],a)):$.isPlainObject(a)&&(a=oneBasedToZeroBased($.extend(!0,{},a)));return void 0==a?"":$.toJSON(a)},preloadImage=function(a){(new Image).src=a},isNumber=function(a){return a===+a},zeroBasedToOneBased=function(a){if($.isArray(a)){for(var b=0;b<a.length;b++)a[b]=zeroBasedToOneBased(a[b]);void 0!==a[0]&&a.splice(0,0,void 0)}else if($.isPlainObject(a))for(b in a)a.hasOwnProperty(b)&&
(a[b]=zeroBasedToOneBased(a[b]));return a},oneBasedToZeroBased=function(a){if($.isArray(a)){for(var b=0;b<a.length;b++)a[b]=oneBasedToZeroBased(a[b]);a.splice(0,1)}else if($.isPlainObject(a))for(b in a)a.hasOwnProperty(b)&&(a[b]=oneBasedToZeroBased(a[b]));return a},getScreenWidth=function(){return document.body.clientWidth},getScreenHeight=function(){return document.body.clientHeight};function getCurrentPageIndex(){return window.foreui.curPage}
function getCurrentPageTitle(){var a=document.getElementById("Page_"+getCurrentPageIndex());return null==a?"":a.getAttribute("pageTitle")}function getAvailablePageIndices(){return window.foreui.pageIndices}function getAvailablePageTitles(){for(var a=[void 0],b=getAvailablePageIndices(),d=1;d<b.length;d++){var c=document.getElementById("Page_"+parseInt(b[d]));null!=c&&a.push(c.getAttribute("pageTitle"))}return a}function getCurrentYear(){return(new Date).getFullYear()}
function getCurrentMonth(){return(new Date).getMonth()+1}function getCurrentDay(){return(new Date).getDate()}function getCurrentHours(){return(new Date).getHours()}function getCurrentMinutes(){return(new Date).getMinutes()}function getCurrentSeconds(){return(new Date).getSeconds()}function getCurrentTimestamp(){return(new Date).getTime()}function getCurrentKeyCode(){var a=getEvent();return null==a?window.foreui.cache.keyCode:a.keyCode}
function getCtrlKeyState(){var a=getEvent();return null!=a&&!0==a.ctrlKey?1:window.foreui.cache.ctrlState}function getAltKeyState(){var a=getEvent();return null!=a&&!0==a.altKey?1:window.foreui.cache.altState}function getShiftKeyState(){var a=getEvent();return null!=a&&!0==a.shiftKey?1:window.foreui.cache.shiftState}function getFocusedElementId(){return window.foreui.focusedElementId}function getCurrentCursorX(){var a=getEvent();return null!=a?a.clientX:-1}
function getCurrentCursorY(){var a=getEvent();return null!=a?a.clientY:-1}function getCurrentEvent(){return window.foreui.currentEvent}
var getElementPropertyValue=function(a,b){switch(b){case "id":return a;case "x":return getBoundsById(a).x;case "y":return getBoundsById(a).y;case "cx":var d=getBoundsById(a);return d.x+d.w/2;case "cy":return d=getBoundsById(a),d.y+d.h/2;case "width":return getBoundsById(a).w;case "height":return getBoundsById(a).h;case "visible":return(d=getForeUIElementById(a))?"hidden"!=d._obj.css("visibility"):!1;case "note":return(d=getForeUIElementById(a))?(d=d._params.note,null==d?"":d):"";default:if(d=getForeUIElementById(a)){var c=
d["get"+b.substring(0,1).toUpperCase()+b.substring(1,b.length)];if(void 0!=c)return c.call(d)}}return null},goToPage=function(a,b,d){window.foreui.curPage==a?b&&b():(window.foreui.lazy&&$("#loading").show(),setTimeout(function(){var c=function(){var c=$(".page").css("visibility","hidden"),e=$("#Page_"+a);if(window.foreui.curPage){var i={};$("#Page_"+window.foreui.curPage).children(".fromMaster").each(function(){var a=$(this).removeClass("fromMaster"),b=a.attr("srcPage");a.removeAttr("srcPage");void 0==
i[b]&&(i[b]=$("<div>/</div>"));i[b].append(a)});for(var l in i)$("#"+l).append(i[l].children())}window.foreui.curPage=a;var j=e.attr("masterPages").split(","),m=$("<div></div>");l=[];for(var k=0;k<j.length;k++)if(""!=j[k]){var n=$("#"+j[k]);n.children(".elem").addClass("fromMaster").attr("srcPage",j[k]).appendTo(m);l.push(n)}m.children().prependTo(e);window.foreui.lazy&&e.find(".elem").each(function(){getForeUIElementById($(this).attr("id"))});e.css("visibility","visible").position({my:window.foreui.align+
" top",at:window.foreui.align+" top",of:document}).css("top","0px");d&&(k="left"==d?"right":"left",k="up"==d?"down":"down"==d?"up":k,e.css("display","none").show("slide",{direction:k},300));for(k=0;k<l.length;k++)l[k].trigger("Loaded_As_Master");e.trigger("Page_Loaded");onPropertyValueChanged("CURRENT_PAGE_INDEX",a);onPropertyValueChanged("CURRENT_PAGE_TITLE",getCurrentPageTitle());var c=c.size(),o=0,q=0;window.foreui.pageIndices=[void 0];for(k=1;k<=c;k++)isPageExcluded(k)||(o++,window.foreui.pageIndices.push(k)),
0==q&&k==a&&(q=o);setTimeout(function(){if(window.foreui.toolbar){ForeUIToolbar.prototype.updatePageIndicator(q,o);ForeUIToolbar.prototype.updateSelectedPage(a)}$("#loading").hide()},50);onPropertyValueChanged("AVAILABLE_PAGE_INDICES",window.foreui.pageIndices);onPropertyValueChanged("AVAILABLE_PAGE_TITLES",getAvailablePageTitles());b&&b()},e=$("#Page_"+window.foreui.curPage);e.trigger("Page_Unloaded");d&&0<e.length?e.hide("slide",{direction:d},300,function(){e.css("display","block");c()}):c()},0))},
previousPage=function(a){for(var b=getCurrentPageIndex()-1;isPageExcluded(b);)b-=1;1<=b&&goToPage(b,void 0,a)},nextPage=function(a){for(var b=getCurrentPageIndex(),d=$(".page").size(),b=b+1;isPageExcluded(b);)b+=1;b<=d&&goToPage(b,void 0,a)},setGlobalCursor=function(a){$("body").css("cursor",a)},changeVisibility=function(a,b,d){var c=getBoundsByIds(a,[]);d&&appendInnerObjects(c,a);for(d=0;d<a.length;d++){var c=getForeUIElementById(a[d])._obj,e=c.get(0),f=0==b?"hidden":1==b?"inherit":"inherit"==e.style.visibility?
"hidden":"inherit";e.style.visibility=f;"hidden"==f?c.trigger("Hidden"):"inherit"==f&&c.trigger("Visible")}},changeState=function(a,b,d){var c=getBoundsByIds(a,[]);d&&appendInnerObjects(c,a);for(d=0;d<a.length;d++)(c=getForeUIElementById(a[d]))&&setState(c,b,!0)},move=function(a,b,d,c){var e=(b+"  ").substring(0,2),f=(d+"  ").substring(0,2),e="+="==e?1:"-="==e?-1:0,f="+="==f?1:"-="==f?-1:0,b=parseFloat(0==e?b:eval(b.substring(2))),d=parseFloat(0==f?d:eval(d.substring(2))),g=[],i=getBoundsByIds(a,
g);c&&appendInnerObjects(i,a);for(c=0;c<a.length;c++){void 0==g[c]&&(g[c]=getBoundsById(a[c]));var l=getForeUIElementById(a[c])._obj.get(0);l.style.left=0==e?b+g[c].x-i.x-g[c].parentX+"px":parseInt(l.style.left)+e*b+"px";l.style.top=0==f?d+g[c].y-i.y-g[c].parentY+"px":parseInt(l.style.top)+f*d+"px"}},resize=function(a,b,d,c){var e=(b+"  ").substring(0,2),f=(d+"  ").substring(0,2),e="+="==e?1:"-="==e?-1:0,f="+="==f?1:"-="==f?-1:0,b=parseFloat(0==e?b:eval(b.substring(2))),d=parseFloat(0==f?d:eval(d.substring(2))),
g=[],i=getBoundsByIds(a,g);c&&appendInnerObjects(i,a);for(c=0;c<a.length;c++){void 0==g[c]&&(g[c]=getBoundsById(a[c]));var l,j,m,k;0==e?(l=i.x+(g[c].x-i.x)*b/i.w,m=b*g[c].w/i.w):(m=g[c].w+e*b*g[c].w/i.w,l=g[c].x+e*(g[c].x-i.x)*b/i.w);0==f?(j=i.y+(g[c].y-i.y)*d/i.h,k=d*g[c].h/i.h):(k=g[c].h+f*d*g[c].h/i.h,j=g[c].y+f*(g[c].y-i.y)*d/i.h);(l!=g[c].x||j!=g[c].y)&&move([a[c]],l,j,!1);l=getForeUIElementById(a[c]);l._obj.width(m).height(k);updateElementAndReferences(l)}},changeBgColor=function(a,b){for(var d=
0;d<a.length;d++){var c=getForeUIElementById(a[d]);c&&c.setBgColor&&(c.setBgColor(b),updateElementAndReferences(c))}},changeOpacity=function(a,b){for(var d=0;d<a.length;d++){var c=getForeUIElementById(a[d]);c&&c.setBgOpacity&&(c.setBgOpacity(b),updateElementAndReferences(c))}},changeTextColor=function(a,b){for(var d=0;d<a.length;d++){var c=getForeUIElementById(a[d]);c&&c.setTextColor&&(c.setTextColor(b),updateElementAndReferences(c))}},changeTextValue=function(a,b){for(var d=0;d<a.length;d++){var c=
getForeUIElementById(a[d]);c&&c.setText&&(c.setText(b),updateElementAndReferences(c))}},triggerEvent=function(a,b){if(a)for(var d=0;d<a.length;d++)getForeUIElementById(a[d])._obj.bind(b,{},!1).trigger(b);else $(document).trigger(b)},setCustomProperty=function(a,b,d){if(0==d){if(!isNumber(b))var c=parseFloat(b),b=parseInt(b),b=c==b?b:c}else 2==d&&($.isArray(b)||(b=[b]));b=zeroBasedToOneBased(b);window.foreui.properties[a]={name:a,value:b,type:d};onPropertyValueChanged(a,b)},setSelectedIndex=function(a,
b){for(var d=0;d<a.length;d++)getForeUIElementById(a[d]).setSelectedIndex(b)},getSelectedIndex=function(a){return getForeUIElementById(a).getSelectedIndex()},setSelectedText=function(a,b){for(var d=0;d<a.length;d++)getForeUIElementById(a[d]).setSelectedText(b)},getSelectedText=function(a){return getForeUIElementById(a).getSelectedText()},setCurrentValue=function(a,b){for(var d=0;d<a.length;d++)getForeUIElementById(a[d]).setCurrentValue(b)},getCurrentValue=function(a){return getForeUIElementById(a).getCurrentValue()},
setFocus=function(a){for(var b=0;b<a.length;b++)getForeUIElementById(a[b]).setFocus()},setImageSource=function(a,b){var d=b.match(/\d+/);if(null!=d)for(var d=d[0]+"."+window.foreui.imagetypes[d[0]],c=0;c<a.length;c++)getForeUIElementById(a[c]).setImageSource(d)},setCurrentEvent=function(a){window.foreui.currentEvent=a;onPropertyValueChanged("CURRENT_EVENT",a)},setTooltip=function(a,b){for(var d=0;d<a.length;d++){var c=getForeUIElementById(a[d]);c._params.tooltip=b;""!=b?$("#"+c._id+', [ref="'+c._id+
'"]').attr("title",b):$("#"+c._id+', [ref="'+c._id+'"]').removeAttr("title")}};var GroupFrame=function(a,b){this._id=a;this._params=b;this._obj=$("#"+a);this.init()};
GroupFrame.prototype={init:function(){var a=this._params,b=this;this._obj.empty();this._bg=$('<div class="bg"></div>').appendTo(this._obj);this._bd=$('<div class="bd"></div>').appendTo(this._obj);this._fg=$('<div class="fg"></div>').appendTo(this._obj);var d=a.titleMargin,c=a["ints_"+a.state];$('<div class="title">'+a.title+"</div>").css({position:"absolute","padding-left":d+"px","padding-top":("outer"==c?d:0)+"px","padding-right":d+"px","padding-bottom":"0px"}).appendTo(this._fg);initReferences(this);
setTimeout(function(){setState(b,a.state,!0)},0)},updateUI:function(a){var b=this._params,d=b.state,c=a.children(".bg"),e=a.children(".bd"),f=a.children(".fg"),g=a.width(),i=a.height(),l=getTextSize(b.title,b["f_n_"+d],b["f_s_"+d],b["f_b_"+d]),j=b.titleMargin,m=b.titleOffset,a=b["ints_"+d],k=Math.ceil("inner"==a?l.height+j:"middle"==a?l.height/2:0);e.add(c).css({"border-width":"0px",left:"0px",top:k+"px",width:g+"px",height:i-k+"px"});generateBackgroundAndBorders(d,"",c,e,b);c=b["align_"+d];g="left"==
c?m:"center"==c?(g-l.width)/2-j:g-m-l.width-2*j;f=f.children(".title").css({left:g+"px","background-color":"middle"==a?b["bg_"+d]:"transparent"});applyFontParameters(d,"",f,b)}};$(document).ready(function(){window.foreui||(window.foreui={});window.foreui.lazy=!1;window.foreui.align="center";$(".page").position({my:window.foreui.align+" top",at:window.foreui.align+" top",of:document}).css("top","0px");window.foreui.imagetypes={};window.foreui.elements={};window.foreui.elements.constructors={};window.foreui.cache={};window.foreui.cache.keyCode=-1;window.foreui.cache.altState=0;window.foreui.cache.ctrlState=0;window.foreui.cache.shiftState=0;window.foreui.elements.constructors.Button_srdf_submit=
function(){window.foreui.elements.Button_srdf_submit=new Button("Button_srdf_submit",{bg_32:"#DADADA",f_c_64:"#A0A0A0",bdc_16:"#707070",bdr_br_64:0,bdt_64:"outset",f_u_64:false,bd_t_16:1,f_b_64:false,bdr_tl_32:0,margin:15,bgo_32:255,f_i_64:false,bdsw_amp_16:0,f_b_0:false,bd_paint_0:true,bdr_br_0:0,bd_b_32:1,f_s_16:11,bdr_bl_32:0,bdr_tr_32:0,bd_r_32:1,bdc_32:"#707070",txt_a_0:"center",bdsw_int_16:0,bdw_64:1,gap:5,bdsw_amp_0:0,bd_l_0:1,states:[0,16,32,64],bdc_0:"#707070",bdw_0:1,f_n_16:"Arial",bdsw_amp_32:0,
f_i_16:false,bgo_16:255,bdr_tl_16:0,bd_t_32:1,bd_l_64:1,txt_a_64:"center",f_s_32:11,f_u_0:false,f_i_0:false,bg_64:"#F0F0F0",bd_paint_64:true,bdr_br_32:0,f_u_16:false,bd_b_0:1,f_b_32:false,bdr_br_16:0,bdsw_int_32:0,icon_p:0,bdr_bl_16:0,f_n_64:"Arial",bd_b_64:1,bgo_64:255,bd_t_64:1,bdc_64:"#8D8D8D",bdw_32:1,bdr_tr_0:0,bd_r_0:1,f_s_0:11,txt_a_16:"center",bdsw_int_0:0,bdr_tr_64:0,f_c_16:"#000000",bd_r_64:1,bdr_tl_64:0,bdr_bl_64:0,bounds:{height:26,width:62,y:0,x:0},bd_t_0:1,f_b_16:false,f_i_32:false,
f_u_32:false,bd_l_16:1,bdt_16:"outset",bd_paint_32:true,bdt_0:"outset",state:0,bg_16:"#DADADA",txt_a_32:"center",bdsw_int_64:0,f_c_32:"#000000",bdw_16:1,f_c_0:"#000000",bg_0:"#E6E6E6",icon:false,bdt_32:"inset",bd_l_32:1,f_n_32:"Arial",bdr_tr_16:0,bdsw_amp_64:0,bd_r_16:1,bd_b_16:1,bdr_bl_0:0,f_n_0:"Arial",bgo_0:255,bdr_tl_0:0,f_s_64:11,bd_paint_16:true})};window.foreui.elements.constructors.Button_ar_submit=function(){window.foreui.elements.Button_ar_submit=new Button("Button_ar_submit",{bg_32:"#DADADA",
f_c_64:"#A0A0A0",bdc_16:"#707070",bdr_br_64:0,bdt_64:"outset",f_u_64:false,bd_t_16:1,f_b_64:false,bdr_tl_32:0,margin:15,bgo_32:255,f_i_64:false,bdsw_amp_16:0,f_b_0:false,bd_paint_0:true,bdr_br_0:0,bd_b_32:1,f_s_16:11,bdr_bl_32:0,bdr_tr_32:0,bd_r_32:1,bdc_32:"#707070",txt_a_0:"center",bdsw_int_16:0,bdw_64:1,gap:5,bdsw_amp_0:0,bd_l_0:1,states:[0,16,32,64],bdc_0:"#707070",bdw_0:1,f_n_16:"Arial",bdsw_amp_32:0,f_i_16:false,bgo_16:255,bdr_tl_16:0,bd_t_32:1,bd_l_64:1,txt_a_64:"center",f_s_32:11,f_u_0:false,
f_i_0:false,bg_64:"#F0F0F0",bd_paint_64:true,bdr_br_32:0,f_u_16:false,bd_b_0:1,f_b_32:false,bdr_br_16:0,bdsw_int_32:0,icon_p:0,bdr_bl_16:0,f_n_64:"Arial",bd_b_64:1,bgo_64:255,bd_t_64:1,bdc_64:"#8D8D8D",bdw_32:1,bdr_tr_0:0,bd_r_0:1,f_s_0:11,txt_a_16:"center",bdsw_int_0:0,bdr_tr_64:0,f_c_16:"#000000",bd_r_64:1,bdr_tl_64:0,bdr_bl_64:0,bounds:{height:26,width:62,y:0,x:0},bd_t_0:1,f_b_16:false,f_i_32:false,f_u_32:false,bd_l_16:1,bdt_16:"outset",bd_paint_32:true,bdt_0:"outset",state:0,bg_16:"#DADADA",txt_a_32:"center",
bdsw_int_64:0,f_c_32:"#000000",bdw_16:1,f_c_0:"#000000",bg_0:"#E6E6E6",icon:false,bdt_32:"inset",bd_l_32:1,f_n_32:"Arial",bdr_tr_16:0,bdsw_amp_64:0,bd_r_16:1,bd_b_16:1,bdr_bl_0:0,f_n_0:"Arial",bgo_0:255,bdr_tl_0:0,f_s_64:11,bd_paint_16:true})};window.foreui.elements.constructors.Button_start=function(){window.foreui.elements.Button_start=new Button("Button_start",{bg_32:"#DADADA",f_c_64:"#A0A0A0",bdc_16:"#707070",bdr_br_64:0,bdt_64:"outset",f_u_64:false,bd_t_16:1,f_b_64:false,bdr_tl_32:0,margin:15,
bgo_32:255,f_i_64:false,bdsw_amp_16:0,f_b_0:false,bd_paint_0:true,bdr_br_0:0,bd_b_32:1,f_s_16:11,bdr_bl_32:0,bdr_tr_32:0,bd_r_32:1,bdc_32:"#707070",txt_a_0:"center",bdsw_int_16:0,bdw_64:1,gap:5,bdsw_amp_0:0,bd_l_0:1,states:[0,16,32,64],bdc_0:"#707070",bdw_0:1,f_n_16:"Arial",bdsw_amp_32:0,f_i_16:false,bgo_16:255,bdr_tl_16:0,bd_t_32:1,bd_l_64:1,txt_a_64:"center",f_s_32:11,f_u_0:false,f_i_0:false,bg_64:"#F0F0F0",bd_paint_64:true,bdr_br_32:0,f_u_16:false,bd_b_0:1,f_b_32:false,bdr_br_16:0,bdsw_int_32:0,
icon_p:0,bdr_bl_16:0,f_n_64:"Arial",bd_b_64:1,bgo_64:255,bd_t_64:1,bdc_64:"#8D8D8D",bdw_32:1,bdr_tr_0:0,bd_r_0:1,f_s_0:11,txt_a_16:"center",bdsw_int_0:0,bdr_tr_64:0,f_c_16:"#000000",bd_r_64:1,bdr_tl_64:0,bdr_bl_64:0,bounds:{height:26,width:53,y:0,x:0},bd_t_0:1,f_b_16:false,f_i_32:false,f_u_32:false,bd_l_16:1,bdt_16:"outset",bd_paint_32:true,bdt_0:"outset",state:0,bg_16:"#DADADA",txt_a_32:"center",bdsw_int_64:0,f_c_32:"#000000",bdw_16:1,f_c_0:"#000000",bg_0:"#E6E6E6",icon:false,bdt_32:"inset",bd_l_32:1,
f_n_32:"Arial",bdr_tr_16:0,bdsw_amp_64:0,bd_r_16:1,bd_b_16:1,bdr_bl_0:0,f_n_0:"Arial",bgo_0:255,bdr_tl_0:0,f_s_64:11,bd_paint_16:true})};window.foreui.elements.constructors.Balloon_1=function(){window.foreui.elements.Balloon_1=new Balloon("Balloon_1",{bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,tipOffset:0.15,bdc_0:"#808080",bdw_0:1,rootOffset:0.05,bd_r_0:1,bdr_tr_0:0,dir:0,f_s_0:13,rootWidth:0.1,bdsw_int_0:0,f_c_0:"#073F00",margin:5,bg_0:"#F4FFE9",f_b_0:true,bd_paint_0:true,f_i_0:false,f_u_0:false,
bdr_br_0:0,bounds:{height:34,width:250,y:151,x:500},bdr_bl_0:0,f_n_0:"Arial",bd_t_0:1,bgo_0:255,bd_b_0:1,txt_a_0:"center",bdr_tl_0:0,tipLength:0.2})};window.foreui.elements.constructors.ProgressBar_1=function(){window.foreui.elements.ProgressBar_1=new ProgressBar("ProgressBar_1",{bdsw_amp_0:0,bd_l_0:1,indm:1,bdt_0:"solid",indc:"#DADADA",bdc_0:"#808080",bdw_0:1,bd_r_0:1,bdr_tr_0:0,indw:10,bdsw_int_0:0,indt:false,bg_0:"transparent",min:0,max:10,bd_paint_0:true,bdr_br_0:0,bounds:{height:20,width:1144,
y:0,x:0},bdr_bl_0:0,bd_t_0:1,bgo_0:255,bd_b_0:1,tile:true,bdr_tl_0:0,cur:4,step:1})};window.foreui.elements.constructors.List_1=function(){window.foreui.elements.List_1=new List("List_1",{rowbdw_64:0,rowbdr_tl_64:0,selbd_paint_64:true,altbd_paint_64:true,altf_u_0:false,bdr_br_64:0,bdt_64:"solid",txtm:10,selbdr_bl_0:0,altbdw_64:0,selbd_b_0:0,self_s_64:11,rowbdr_tl_0:0,rowbdr_br_0:0,rowbdc_64:"#C0C0C0",altbdt_0:"none",selbd_t_64:0,altf_b_64:false,rowbgo_0:255,rowbdt_0:"none",bd_paint_0:true,rowf_i_0:false,
bdr_br_0:0,altbdt_64:"none",altf_u_64:false,altbg_0:"#F0F0F0",selbdr_bl_64:0,selbd_t_0:0,altbdr_tr_64:0,rowbdsw_amp_0:0,bdw_64:1,selbd_r_0:0,altf_c_64:"#808080",gap:5,bdsw_amp_0:0,bd_l_0:1,rowf_u_64:false,self_s_0:11,selbdr_tr_64:0,states:[0,64],bdc_0:"#808080",bdw_0:1,altbd_r_64:0,selbdr_br_64:0,altf_b_0:false,altf_n_0:"Arial",altf_i_0:false,altbgo_0:255,selbd_r_64:0,self_n_64:"Arial",selbdsw_int_0:0,rowbd_r_64:0,rowbd_b_0:0,self_b_0:false,self_b_64:false,altbd_l_64:0,selbd_paint_0:true,selr:0,selbgo_0:255,
self_u_0:false,bd_l_64:1,selbd_l_0:0,rowbdr_tr_64:0,selbdr_tr_0:0,selbdc_0:"#808080",self_i_64:false,selbdw_64:0,altbd_paint_0:true,bg_64:"#FFFFFF",bd_paint_64:true,rowbd_r_0:0,rowbdr_tr_0:0,rowbd_t_0:0,self_i_0:false,bd_b_0:1,pbdr_64:true,rowf_s_64:11,altbgo_64:255,selbdc_64:"#C0C0C0",rowbounds:{height:691,width:327,y:0,x:0},selbd_l_64:0,rowf_n_0:"Arial",rowbg_0:"#FFFFFF",altbd_b_64:0,horl_0:true,bd_b_64:1,rowbdsw_amp_64:0,altbdr_bl_64:0,bgo_64:255,altbdc_64:"#C0C0C0",selbdt_64:"none",bd_t_64:1,
rowbd_paint_0:true,rowbdw_0:0,rowbdsw_int_0:0,bdc_64:"#C0C0C0",self_n_0:"Arial",altbdsw_amp_64:0,bd_r_0:1,bdr_tr_0:0,altbd_l_0:0,rowbd_b_64:0,rowf_s_0:11,bdsw_int_0:0,bdr_tr_64:0,rowbdc_0:"#808080",selbg_0:"#D7D7D7",altbd_r_0:0,selbd_b_64:0,bd_r_64:1,self_c_0:"#000000",altbdr_tl_0:0,rowf_i_64:false,rowbd_t_64:0,selbdt_0:"none",bdr_tl_64:0,altbdr_bl_0:0,bdr_bl_64:0,altf_s_64:11,rows:3,bounds:{height:691,width:327,y:0,x:0},bd_t_0:1,rowbd_paint_64:true,altf_c_0:"#000000",rowh:25,rowf_u_0:false,self_u_64:false,
selbdr_tl_64:0,selbdr_tl_0:0,altbd_b_0:0,altbdr_br_0:0,rowbdr_bl_0:0,selbdsw_amp_64:0,rowf_b_0:false,bdt_0:"solid",selbdsw_int_64:0,state:0,altbounds:{height:691,width:327,y:0,x:0},altbdr_tl_64:0,altbdc_0:"#808080",selbdr_br_0:0,bdsw_int_64:0,rowf_c_64:"#808080",rowf_c_0:"#000000",altbd_t_64:0,selbdw_0:0,altbg_64:"#F0F0F0",altf_i_64:false,pbdr_0:true,rowbd_l_0:0,rowbdsw_int_64:0,altbdsw_int_64:0,self_c_64:"#808080",selbgo_64:255,altbdr_tr_0:0,rowbd_l_64:0,horl_64:true,bg_0:"#FFFFFF",rowbdt_64:"none",
altbdsw_amp_0:0,rowbg_64:"#FFFFFF",altbd_t_0:0,bdsw_amp_64:0,rowbgo_64:255,rowbdr_br_64:0,altbdsw_int_0:0,altbdr_br_64:0,altf_n_64:"Arial",bdr_bl_0:0,rowf_n_64:"Arial",rowf_b_64:false,bgo_0:255,altbdw_0:0,selbg_64:"#D7D7D7",selbounds:{height:691,width:327,y:0,x:0},selbdsw_amp_0:0,bdr_tl_0:0,rowbdr_bl_64:0,icons:[null,null,null],altf_s_0:11})};window.foreui.elements.constructors.RadioButton_strue=function(){window.foreui.elements.RadioButton_strue=new RadioButton("RadioButton_strue",{bd_l_48:0,bg_32:"#000000",
f_c_64:"#B2B2B2",gap_0:5,bdsw_amp_96:0,bd_paint_96:true,bdc_16:"#808080",bdr_br_64:0,bdt_64:"none",f_u_64:false,gap_32:5,bd_t_16:0,f_b_64:false,bdr_tl_32:0,icon_64:"RadioButton_Icon__Disabled.png",f_s_96:11,bgo_32:0,f_i_64:false,bdsw_amp_16:0,bdsw_int_96:0,f_b_0:false,f_n_96:"Arial",bd_paint_0:true,bg_48:"#000000",bdr_br_0:0,bd_b_32:0,f_s_16:11,bdr_bl_32:0,bdr_br_48:0,bdr_tr_32:0,bd_r_32:0,bdc_32:"#808080",bdsw_int_16:0,icon_16:"RadioButton_Icon__Hovering.png",bdw_64:0,bdsw_amp_0:0,bd_l_0:0,bdr_bl_96:0,
bdr_tl_96:0,bd_b_48:0,gap_96:5,states:[0,16,32,48,96,64],bdc_0:"#808080",f_c_48:"#3A3A3A",bdw_0:0,gap_16:5,f_n_16:"Arial",bdr_tr_48:0,bdsw_amp_32:0,bd_r_48:0,f_i_16:false,bgo_16:0,f_b_48:false,bdr_tl_16:0,bd_t_32:0,icon_48:"RadioButton_Icon__Selected_Hovering.png",bd_l_64:0,f_s_32:11,f_i_0:false,f_u_0:false,bg_64:"#000000",bd_t_96:0,bdc_96:"#808080",f_u_96:false,bgo_96:0,bd_paint_64:true,bdr_br_32:0,icon_32:"RadioButton_Icon__Selected.png",f_u_16:false,bd_b_0:0,bdr_br_16:0,f_b_32:false,icon_p:0,bdsw_int_32:0,
bdw_48:0,f_i_96:false,bdr_bl_16:0,f_n_64:"Arial",bdsw_int_48:0,bd_b_64:0,icon_0:"RadioButton_Icon__Normal.png",bgo_64:0,bd_t_64:0,bdc_64:"#808080",bdt_96:"none",bdw_32:0,bdr_tr_0:0,bd_r_0:0,f_s_0:11,bdr_tr_64:0,bdsw_int_0:0,bd_paint_48:true,f_c_16:"#3A3A3A",bd_r_64:0,text:"True",bdr_br_96:0,bdsw_amp_48:0,bdr_tl_64:0,f_b_96:false,bdr_bl_64:0,bounds:{height:26,width:58,y:0,x:0},bd_t_0:0,bd_l_96:0,gap_64:5,f_s_48:11,f_u_32:false,f_i_32:false,f_b_16:false,bd_l_16:0,bdt_16:"none",f_n_48:"Arial",bd_paint_32:true,
bd_t_48:0,bdt_0:"none",bgo_48:0,state:0,bdw_96:0,bg_16:"#000000",bdsw_int_64:0,f_i_48:false,f_c_32:"#000000",bg_96:"#000000",bdw_16:0,f_u_48:false,f_c_0:"#000000",bdt_48:"none",bg_0:"#000000",bdr_tr_96:0,bdt_32:"none",bdr_tl_48:0,bdr_bl_48:0,f_n_32:"Arial",bd_l_32:0,bd_b_96:0,bdr_tr_16:0,bdsw_amp_64:0,bd_r_16:0,f_c_96:"#B2B2B2",bd_b_16:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,bdc_48:"#808080",bd_r_96:0,bdr_tl_0:0,gap_48:5,f_s_64:11,icon_96:"RadioButton_Icon__Selected_Disabled.png",bd_paint_16:true})};window.foreui.elements.constructors.RadioButton_sfalse=
function(){window.foreui.elements.RadioButton_sfalse=new RadioButton("RadioButton_sfalse",{bd_l_48:0,bg_32:"#000000",f_c_64:"#B2B2B2",gap_0:5,bdsw_amp_96:0,bd_paint_96:true,bdc_16:"#808080",bdr_br_64:0,bdt_64:"none",f_u_64:false,gap_32:5,bd_t_16:0,f_b_64:false,bdr_tl_32:0,icon_64:"RadioButton_Icon__Disabled.png",f_s_96:11,bgo_32:0,f_i_64:false,bdsw_amp_16:0,bdsw_int_96:0,f_b_0:false,f_n_96:"Arial",bd_paint_0:true,bg_48:"#000000",bdr_br_0:0,bd_b_32:0,f_s_16:11,bdr_bl_32:0,bdr_br_48:0,bdr_tr_32:0,bd_r_32:0,
bdc_32:"#808080",bdsw_int_16:0,icon_16:"RadioButton_Icon__Hovering.png",bdw_64:0,bdsw_amp_0:0,bd_l_0:0,bdr_bl_96:0,bdr_tl_96:0,bd_b_48:0,gap_96:5,states:[0,16,32,48,96,64],bdc_0:"#808080",f_c_48:"#3A3A3A",bdw_0:0,gap_16:5,f_n_16:"Arial",bdr_tr_48:0,bdsw_amp_32:0,bd_r_48:0,f_i_16:false,bgo_16:0,f_b_48:false,bdr_tl_16:0,bd_t_32:0,icon_48:"RadioButton_Icon__Selected_Hovering.png",bd_l_64:0,f_s_32:11,f_i_0:false,f_u_0:false,bg_64:"#000000",bd_t_96:0,bdc_96:"#808080",f_u_96:false,bgo_96:0,bd_paint_64:true,
bdr_br_32:0,icon_32:"RadioButton_Icon__Selected.png",f_u_16:false,bd_b_0:0,bdr_br_16:0,f_b_32:false,icon_p:0,bdsw_int_32:0,bdw_48:0,f_i_96:false,bdr_bl_16:0,f_n_64:"Arial",bdsw_int_48:0,bd_b_64:0,icon_0:"RadioButton_Icon__Normal.png",bgo_64:0,bd_t_64:0,bdc_64:"#808080",bdt_96:"none",bdw_32:0,bdr_tr_0:0,bd_r_0:0,f_s_0:11,bdr_tr_64:0,bdsw_int_0:0,bd_paint_48:true,f_c_16:"#3A3A3A",bd_r_64:0,text:"False",bdr_br_96:0,bdsw_amp_48:0,bdr_tl_64:0,f_b_96:false,bdr_bl_64:0,bounds:{height:26,width:62,y:0,x:0},
bd_t_0:0,bd_l_96:0,gap_64:5,f_s_48:11,f_u_32:false,f_i_32:false,f_b_16:false,bd_l_16:0,bdt_16:"none",f_n_48:"Arial",bd_paint_32:true,bd_t_48:0,bdt_0:"none",bgo_48:0,state:0,bdw_96:0,bg_16:"#000000",bdsw_int_64:0,f_i_48:false,f_c_32:"#000000",bg_96:"#000000",bdw_16:0,f_u_48:false,f_c_0:"#000000",bdt_48:"none",bg_0:"#000000",bdr_tr_96:0,bdt_32:"none",bdr_tl_48:0,bdr_bl_48:0,f_n_32:"Arial",bd_l_32:0,bd_b_96:0,bdr_tr_16:0,bdsw_amp_64:0,bd_r_16:0,f_c_96:"#B2B2B2",bd_b_16:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,
bdc_48:"#808080",bd_r_96:0,bdr_tl_0:0,gap_48:5,f_s_64:11,icon_96:"RadioButton_Icon__Selected_Disabled.png",bd_paint_16:true})};window.foreui.elements.constructors.RadioButton_a2true=function(){window.foreui.elements.RadioButton_a2true=new RadioButton("RadioButton_a2true",{bd_l_48:0,bg_32:"#000000",f_c_64:"#B2B2B2",gap_0:5,bdsw_amp_96:0,bd_paint_96:true,bdc_16:"#808080",bdr_br_64:0,bdt_64:"none",f_u_64:false,gap_32:5,bd_t_16:0,f_b_64:false,bdr_tl_32:0,icon_64:"RadioButton_Icon__Disabled.png",f_s_96:11,
bgo_32:0,f_i_64:false,bdsw_amp_16:0,bdsw_int_96:0,f_b_0:false,f_n_96:"Arial",bd_paint_0:true,bg_48:"#000000",bdr_br_0:0,bd_b_32:0,f_s_16:11,bdr_bl_32:0,bdr_br_48:0,bdr_tr_32:0,bd_r_32:0,bdc_32:"#808080",bdsw_int_16:0,icon_16:"RadioButton_Icon__Hovering.png",bdw_64:0,bdsw_amp_0:0,bd_l_0:0,bdr_bl_96:0,bdr_tl_96:0,bd_b_48:0,gap_96:5,states:[0,16,32,48,96,64],bdc_0:"#808080",f_c_48:"#3A3A3A",bdw_0:0,gap_16:5,f_n_16:"Arial",bdr_tr_48:0,bdsw_amp_32:0,bd_r_48:0,f_i_16:false,bgo_16:0,f_b_48:false,bdr_tl_16:0,
bd_t_32:0,icon_48:"RadioButton_Icon__Selected_Hovering.png",bd_l_64:0,f_s_32:11,f_i_0:false,f_u_0:false,bg_64:"#000000",bd_t_96:0,bdc_96:"#808080",f_u_96:false,bgo_96:0,bd_paint_64:true,bdr_br_32:0,icon_32:"RadioButton_Icon__Selected.png",f_u_16:false,bd_b_0:0,bdr_br_16:0,f_b_32:false,icon_p:0,bdsw_int_32:0,bdw_48:0,f_i_96:false,bdr_bl_16:0,f_n_64:"Arial",bdsw_int_48:0,bd_b_64:0,icon_0:"RadioButton_Icon__Normal.png",bgo_64:0,bd_t_64:0,bdc_64:"#808080",bdt_96:"none",bdw_32:0,bdr_tr_0:0,bd_r_0:0,f_s_0:11,
bdr_tr_64:0,bdsw_int_0:0,bd_paint_48:true,f_c_16:"#3A3A3A",bd_r_64:0,text:"True",bdr_br_96:0,bdsw_amp_48:0,bdr_tl_64:0,f_b_96:false,bdr_bl_64:0,bounds:{height:26,width:58,y:0,x:0},bd_t_0:0,bd_l_96:0,gap_64:5,f_s_48:11,f_u_32:false,f_i_32:false,f_b_16:false,bd_l_16:0,bdt_16:"none",f_n_48:"Arial",bd_paint_32:true,bd_t_48:0,bdt_0:"none",bgo_48:0,state:0,bdw_96:0,bg_16:"#000000",bdsw_int_64:0,f_i_48:false,f_c_32:"#000000",bg_96:"#000000",bdw_16:0,f_u_48:false,f_c_0:"#000000",bdt_48:"none",bg_0:"#000000",
bdr_tr_96:0,bdt_32:"none",bdr_tl_48:0,bdr_bl_48:0,f_n_32:"Arial",bd_l_32:0,bd_b_96:0,bdr_tr_16:0,bdsw_amp_64:0,bd_r_16:0,f_c_96:"#B2B2B2",bd_b_16:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,bdc_48:"#808080",bd_r_96:0,bdr_tl_0:0,gap_48:5,f_s_64:11,icon_96:"RadioButton_Icon__Selected_Disabled.png",bd_paint_16:true})};window.foreui.elements.constructors.RadioButton_a2false=function(){window.foreui.elements.RadioButton_a2false=new RadioButton("RadioButton_a2false",{bd_l_48:0,bg_32:"#000000",f_c_64:"#B2B2B2",gap_0:5,
bdsw_amp_96:0,bd_paint_96:true,bdc_16:"#808080",bdr_br_64:0,bdt_64:"none",f_u_64:false,gap_32:5,bd_t_16:0,f_b_64:false,bdr_tl_32:0,icon_64:"RadioButton_Icon__Disabled.png",f_s_96:11,bgo_32:0,f_i_64:false,bdsw_amp_16:0,bdsw_int_96:0,f_b_0:false,f_n_96:"Arial",bd_paint_0:true,bg_48:"#000000",bdr_br_0:0,bd_b_32:0,f_s_16:11,bdr_bl_32:0,bdr_br_48:0,bdr_tr_32:0,bd_r_32:0,bdc_32:"#808080",bdsw_int_16:0,icon_16:"RadioButton_Icon__Hovering.png",bdw_64:0,bdsw_amp_0:0,bd_l_0:0,bdr_bl_96:0,bdr_tl_96:0,bd_b_48:0,
gap_96:5,states:[0,16,32,48,96,64],bdc_0:"#808080",f_c_48:"#3A3A3A",bdw_0:0,gap_16:5,f_n_16:"Arial",bdr_tr_48:0,bdsw_amp_32:0,bd_r_48:0,f_i_16:false,bgo_16:0,f_b_48:false,bdr_tl_16:0,bd_t_32:0,icon_48:"RadioButton_Icon__Selected_Hovering.png",bd_l_64:0,f_s_32:11,f_i_0:false,f_u_0:false,bg_64:"#000000",bd_t_96:0,bdc_96:"#808080",f_u_96:false,bgo_96:0,bd_paint_64:true,bdr_br_32:0,icon_32:"RadioButton_Icon__Selected.png",f_u_16:false,bd_b_0:0,bdr_br_16:0,f_b_32:false,icon_p:0,bdsw_int_32:0,bdw_48:0,
f_i_96:false,bdr_bl_16:0,f_n_64:"Arial",bdsw_int_48:0,bd_b_64:0,icon_0:"RadioButton_Icon__Normal.png",bgo_64:0,bd_t_64:0,bdc_64:"#808080",bdt_96:"none",bdw_32:0,bdr_tr_0:0,bd_r_0:0,f_s_0:11,bdr_tr_64:0,bdsw_int_0:0,bd_paint_48:true,f_c_16:"#3A3A3A",bd_r_64:0,text:"False",bdr_br_96:0,bdsw_amp_48:0,bdr_tl_64:0,f_b_96:false,bdr_bl_64:0,bounds:{height:26,width:62,y:0,x:0},bd_t_0:0,bd_l_96:0,gap_64:5,f_s_48:11,f_u_32:false,f_i_32:false,f_b_16:false,bd_l_16:0,bdt_16:"none",f_n_48:"Arial",bd_paint_32:true,
bd_t_48:0,bdt_0:"none",bgo_48:0,state:0,bdw_96:0,bg_16:"#000000",bdsw_int_64:0,f_i_48:false,f_c_32:"#000000",bg_96:"#000000",bdw_16:0,f_u_48:false,f_c_0:"#000000",bdt_48:"none",bg_0:"#000000",bdr_tr_96:0,bdt_32:"none",bdr_tl_48:0,bdr_bl_48:0,f_n_32:"Arial",bd_l_32:0,bd_b_96:0,bdr_tr_16:0,bdsw_amp_64:0,bd_r_16:0,f_c_96:"#B2B2B2",bd_b_16:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,bdc_48:"#808080",bd_r_96:0,bdr_tl_0:0,gap_48:5,f_s_64:11,icon_96:"RadioButton_Icon__Selected_Disabled.png",bd_paint_16:true})};window.foreui.elements.constructors.RadioButton_rtrue=
function(){window.foreui.elements.RadioButton_rtrue=new RadioButton("RadioButton_rtrue",{bd_l_48:0,bg_32:"#000000",f_c_64:"#B2B2B2",gap_0:5,bdsw_amp_96:0,bd_paint_96:true,bdc_16:"#808080",bdr_br_64:0,bdt_64:"none",f_u_64:false,gap_32:5,bd_t_16:0,f_b_64:false,bdr_tl_32:0,icon_64:"RadioButton_Icon__Disabled.png",f_s_96:11,bgo_32:0,f_i_64:false,bdsw_amp_16:0,bdsw_int_96:0,f_b_0:false,f_n_96:"Arial",bd_paint_0:true,bg_48:"#000000",bdr_br_0:0,bd_b_32:0,f_s_16:11,bdr_bl_32:0,bdr_br_48:0,bdr_tr_32:0,bd_r_32:0,
bdc_32:"#808080",bdsw_int_16:0,icon_16:"RadioButton_Icon__Hovering.png",bdw_64:0,bdsw_amp_0:0,bd_l_0:0,bdr_bl_96:0,bdr_tl_96:0,bd_b_48:0,gap_96:5,states:[0,16,32,48,96,64],bdc_0:"#808080",f_c_48:"#3A3A3A",bdw_0:0,gap_16:5,f_n_16:"Arial",bdr_tr_48:0,bdsw_amp_32:0,bd_r_48:0,f_i_16:false,bgo_16:0,f_b_48:false,bdr_tl_16:0,bd_t_32:0,icon_48:"RadioButton_Icon__Selected_Hovering.png",bd_l_64:0,f_s_32:11,f_i_0:false,f_u_0:false,bg_64:"#000000",bd_t_96:0,bdc_96:"#808080",f_u_96:false,bgo_96:0,bd_paint_64:true,
bdr_br_32:0,icon_32:"RadioButton_Icon__Selected.png",f_u_16:false,bd_b_0:0,bdr_br_16:0,f_b_32:false,icon_p:0,bdsw_int_32:0,bdw_48:0,f_i_96:false,bdr_bl_16:0,f_n_64:"Arial",bdsw_int_48:0,bd_b_64:0,icon_0:"RadioButton_Icon__Normal.png",bgo_64:0,bd_t_64:0,bdc_64:"#808080",bdt_96:"none",bdw_32:0,bdr_tr_0:0,bd_r_0:0,f_s_0:11,bdr_tr_64:0,bdsw_int_0:0,bd_paint_48:true,f_c_16:"#3A3A3A",bd_r_64:0,text:"True",bdr_br_96:0,bdsw_amp_48:0,bdr_tl_64:0,f_b_96:false,bdr_bl_64:0,bounds:{height:26,width:58,y:0,x:0},
bd_t_0:0,bd_l_96:0,gap_64:5,f_s_48:11,f_u_32:false,f_i_32:false,f_b_16:false,bd_l_16:0,bdt_16:"none",f_n_48:"Arial",bd_paint_32:true,bd_t_48:0,bdt_0:"none",bgo_48:0,state:0,bdw_96:0,bg_16:"#000000",bdsw_int_64:0,f_i_48:false,f_c_32:"#000000",bg_96:"#000000",bdw_16:0,f_u_48:false,f_c_0:"#000000",bdt_48:"none",bg_0:"#000000",bdr_tr_96:0,bdt_32:"none",bdr_tl_48:0,bdr_bl_48:0,f_n_32:"Arial",bd_l_32:0,bd_b_96:0,bdr_tr_16:0,bdsw_amp_64:0,bd_r_16:0,f_c_96:"#B2B2B2",bd_b_16:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,
bdc_48:"#808080",bd_r_96:0,bdr_tl_0:0,gap_48:5,f_s_64:11,icon_96:"RadioButton_Icon__Selected_Disabled.png",bd_paint_16:true})};window.foreui.elements.constructors.RadioButton_rfalse=function(){window.foreui.elements.RadioButton_rfalse=new RadioButton("RadioButton_rfalse",{bd_l_48:0,bg_32:"#000000",f_c_64:"#B2B2B2",gap_0:5,bdsw_amp_96:0,bd_paint_96:true,bdc_16:"#808080",bdr_br_64:0,bdt_64:"none",f_u_64:false,gap_32:5,bd_t_16:0,f_b_64:false,bdr_tl_32:0,icon_64:"RadioButton_Icon__Disabled.png",f_s_96:11,
bgo_32:0,f_i_64:false,bdsw_amp_16:0,bdsw_int_96:0,f_b_0:false,f_n_96:"Arial",bd_paint_0:true,bg_48:"#000000",bdr_br_0:0,bd_b_32:0,f_s_16:11,bdr_bl_32:0,bdr_br_48:0,bdr_tr_32:0,bd_r_32:0,bdc_32:"#808080",bdsw_int_16:0,icon_16:"RadioButton_Icon__Hovering.png",bdw_64:0,bdsw_amp_0:0,bd_l_0:0,bdr_bl_96:0,bdr_tl_96:0,bd_b_48:0,gap_96:5,states:[0,16,32,48,96,64],bdc_0:"#808080",f_c_48:"#3A3A3A",bdw_0:0,gap_16:5,f_n_16:"Arial",bdr_tr_48:0,bdsw_amp_32:0,bd_r_48:0,f_i_16:false,bgo_16:0,f_b_48:false,bdr_tl_16:0,
bd_t_32:0,icon_48:"RadioButton_Icon__Selected_Hovering.png",bd_l_64:0,f_s_32:11,f_i_0:false,f_u_0:false,bg_64:"#000000",bd_t_96:0,bdc_96:"#808080",f_u_96:false,bgo_96:0,bd_paint_64:true,bdr_br_32:0,icon_32:"RadioButton_Icon__Selected.png",f_u_16:false,bd_b_0:0,bdr_br_16:0,f_b_32:false,icon_p:0,bdsw_int_32:0,bdw_48:0,f_i_96:false,bdr_bl_16:0,f_n_64:"Arial",bdsw_int_48:0,bd_b_64:0,icon_0:"RadioButton_Icon__Normal.png",bgo_64:0,bd_t_64:0,bdc_64:"#808080",bdt_96:"none",bdw_32:0,bdr_tr_0:0,bd_r_0:0,f_s_0:11,
bdr_tr_64:0,bdsw_int_0:0,bd_paint_48:true,f_c_16:"#3A3A3A",bd_r_64:0,text:"False",bdr_br_96:0,bdsw_amp_48:0,bdr_tl_64:0,f_b_96:false,bdr_bl_64:0,bounds:{height:26,width:62,y:0,x:0},bd_t_0:0,bd_l_96:0,gap_64:5,f_s_48:11,f_u_32:false,f_i_32:false,f_b_16:false,bd_l_16:0,bdt_16:"none",f_n_48:"Arial",bd_paint_32:true,bd_t_48:0,bdt_0:"none",bgo_48:0,state:0,bdw_96:0,bg_16:"#000000",bdsw_int_64:0,f_i_48:false,f_c_32:"#000000",bg_96:"#000000",bdw_16:0,f_u_48:false,f_c_0:"#000000",bdt_48:"none",bg_0:"#000000",
bdr_tr_96:0,bdt_32:"none",bdr_tl_48:0,bdr_bl_48:0,f_n_32:"Arial",bd_l_32:0,bd_b_96:0,bdr_tr_16:0,bdsw_amp_64:0,bd_r_16:0,f_c_96:"#B2B2B2",bd_b_16:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,bdc_48:"#808080",bd_r_96:0,bdr_tl_0:0,gap_48:5,f_s_64:11,icon_96:"RadioButton_Icon__Selected_Disabled.png",bd_paint_16:true})};window.foreui.elements.constructors.RadioButton_a1false=function(){window.foreui.elements.RadioButton_a1false=new RadioButton("RadioButton_a1false",{bd_l_48:0,bg_32:"#000000",f_c_64:"#B2B2B2",gap_0:5,
bdsw_amp_96:0,bd_paint_96:true,bdc_16:"#808080",bdr_br_64:0,bdt_64:"none",f_u_64:false,gap_32:5,bd_t_16:0,f_b_64:false,bdr_tl_32:0,icon_64:"RadioButton_Icon__Disabled.png",f_s_96:11,bgo_32:0,f_i_64:false,bdsw_amp_16:0,bdsw_int_96:0,f_b_0:false,f_n_96:"Arial",bd_paint_0:true,bg_48:"#000000",bdr_br_0:0,bd_b_32:0,f_s_16:11,bdr_bl_32:0,bdr_br_48:0,bdr_tr_32:0,bd_r_32:0,bdc_32:"#808080",bdsw_int_16:0,icon_16:"RadioButton_Icon__Hovering.png",bdw_64:0,bdsw_amp_0:0,bd_l_0:0,bdr_bl_96:0,bdr_tl_96:0,bd_b_48:0,
gap_96:5,states:[0,16,32,48,96,64],bdc_0:"#808080",f_c_48:"#3A3A3A",bdw_0:0,gap_16:5,f_n_16:"Arial",bdr_tr_48:0,bdsw_amp_32:0,bd_r_48:0,f_i_16:false,bgo_16:0,f_b_48:false,bdr_tl_16:0,bd_t_32:0,icon_48:"RadioButton_Icon__Selected_Hovering.png",bd_l_64:0,f_s_32:11,f_i_0:false,f_u_0:false,bg_64:"#000000",bd_t_96:0,bdc_96:"#808080",f_u_96:false,bgo_96:0,bd_paint_64:true,bdr_br_32:0,icon_32:"RadioButton_Icon__Selected.png",f_u_16:false,bd_b_0:0,bdr_br_16:0,f_b_32:false,icon_p:0,bdsw_int_32:0,bdw_48:0,
f_i_96:false,bdr_bl_16:0,f_n_64:"Arial",bdsw_int_48:0,bd_b_64:0,icon_0:"RadioButton_Icon__Normal.png",bgo_64:0,bd_t_64:0,bdc_64:"#808080",bdt_96:"none",bdw_32:0,bdr_tr_0:0,bd_r_0:0,f_s_0:11,bdr_tr_64:0,bdsw_int_0:0,bd_paint_48:true,f_c_16:"#3A3A3A",bd_r_64:0,text:"False",bdr_br_96:0,bdsw_amp_48:0,bdr_tl_64:0,f_b_96:false,bdr_bl_64:0,bounds:{height:26,width:62,y:0,x:0},bd_t_0:0,bd_l_96:0,gap_64:5,f_s_48:11,f_u_32:false,f_i_32:false,f_b_16:false,bd_l_16:0,bdt_16:"none",f_n_48:"Arial",bd_paint_32:true,
bd_t_48:0,bdt_0:"none",bgo_48:0,state:0,bdw_96:0,bg_16:"#000000",bdsw_int_64:0,f_i_48:false,f_c_32:"#000000",bg_96:"#000000",bdw_16:0,f_u_48:false,f_c_0:"#000000",bdt_48:"none",bg_0:"#000000",bdr_tr_96:0,bdt_32:"none",bdr_tl_48:0,bdr_bl_48:0,f_n_32:"Arial",bd_l_32:0,bd_b_96:0,bdr_tr_16:0,bdsw_amp_64:0,bd_r_16:0,f_c_96:"#B2B2B2",bd_b_16:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,bdc_48:"#808080",bd_r_96:0,bdr_tl_0:0,gap_48:5,f_s_64:11,icon_96:"RadioButton_Icon__Selected_Disabled.png",bd_paint_16:true})};window.foreui.elements.constructors.RadioButton_a1true=
function(){window.foreui.elements.RadioButton_a1true=new RadioButton("RadioButton_a1true",{bd_l_48:0,bg_32:"#000000",f_c_64:"#B2B2B2",gap_0:5,bdsw_amp_96:0,bd_paint_96:true,bdc_16:"#808080",bdr_br_64:0,bdt_64:"none",f_u_64:false,gap_32:5,bd_t_16:0,f_b_64:false,bdr_tl_32:0,icon_64:"RadioButton_Icon__Disabled.png",f_s_96:11,bgo_32:0,f_i_64:false,bdsw_amp_16:0,bdsw_int_96:0,f_b_0:false,f_n_96:"Arial",bd_paint_0:true,bg_48:"#000000",bdr_br_0:0,bd_b_32:0,f_s_16:11,bdr_bl_32:0,bdr_br_48:0,bdr_tr_32:0,bd_r_32:0,
bdc_32:"#808080",bdsw_int_16:0,icon_16:"RadioButton_Icon__Hovering.png",bdw_64:0,bdsw_amp_0:0,bd_l_0:0,bdr_bl_96:0,bdr_tl_96:0,bd_b_48:0,gap_96:5,states:[0,16,32,48,96,64],bdc_0:"#808080",f_c_48:"#3A3A3A",bdw_0:0,gap_16:5,f_n_16:"Arial",bdr_tr_48:0,bdsw_amp_32:0,bd_r_48:0,f_i_16:false,bgo_16:0,f_b_48:false,bdr_tl_16:0,bd_t_32:0,icon_48:"RadioButton_Icon__Selected_Hovering.png",bd_l_64:0,f_s_32:11,f_i_0:false,f_u_0:false,bg_64:"#000000",bd_t_96:0,bdc_96:"#808080",f_u_96:false,bgo_96:0,bd_paint_64:true,
bdr_br_32:0,icon_32:"RadioButton_Icon__Selected.png",f_u_16:false,bd_b_0:0,bdr_br_16:0,f_b_32:false,icon_p:0,bdsw_int_32:0,bdw_48:0,f_i_96:false,bdr_bl_16:0,f_n_64:"Arial",bdsw_int_48:0,bd_b_64:0,icon_0:"RadioButton_Icon__Normal.png",bgo_64:0,bd_t_64:0,bdc_64:"#808080",bdt_96:"none",bdw_32:0,bdr_tr_0:0,bd_r_0:0,f_s_0:11,bdr_tr_64:0,bdsw_int_0:0,bd_paint_48:true,f_c_16:"#3A3A3A",bd_r_64:0,text:"True",bdr_br_96:0,bdsw_amp_48:0,bdr_tl_64:0,f_b_96:false,bdr_bl_64:0,bounds:{height:26,width:58,y:0,x:0},
bd_t_0:0,bd_l_96:0,gap_64:5,f_s_48:11,f_u_32:false,f_i_32:false,f_b_16:false,bd_l_16:0,bdt_16:"none",f_n_48:"Arial",bd_paint_32:true,bd_t_48:0,bdt_0:"none",bgo_48:0,state:0,bdw_96:0,bg_16:"#000000",bdsw_int_64:0,f_i_48:false,f_c_32:"#000000",bg_96:"#000000",bdw_16:0,f_u_48:false,f_c_0:"#000000",bdt_48:"none",bg_0:"#000000",bdr_tr_96:0,bdt_32:"none",bdr_tl_48:0,bdr_bl_48:0,f_n_32:"Arial",bd_l_32:0,bd_b_96:0,bdr_tr_16:0,bdsw_amp_64:0,bd_r_16:0,f_c_96:"#B2B2B2",bd_b_16:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,
bdc_48:"#808080",bd_r_96:0,bdr_tl_0:0,gap_48:5,f_s_64:11,icon_96:"RadioButton_Icon__Selected_Disabled.png",bd_paint_16:true})};window.foreui.elements.constructors.TextBox_8=function(){window.foreui.elements.TextBox_8=new TextBox("TextBox_8",{f_n_64:"Arial",f_c_64:"#808080",bd_b_64:1,bgo_64:0,txt_va_64:"top",bd_t_64:1,bdr_br_64:0,bdt_64:"solid",bdc_64:"#C0C0C0",f_u_64:false,f_b_64:true,bd_r_0:1,bdr_tr_0:0,f_s_0:13,bdr_tr_64:0,bdsw_int_0:0,f_i_64:false,bd_r_64:1,f_b_0:true,bd_paint_0:false,bdr_br_0:0,
bdr_tl_64:0,bdr_bl_64:0,bounds:{height:17,width:141,y:0,x:0},bd_t_0:1,txt_a_0:"left",bdw_64:1,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#000000",bdw_0:1,bdsw_int_64:0,f_c_0:"#000000",bd_l_64:1,txt_va_0:"top",bg_0:"#FFFFFF",txt_a_64:"left",f_u_0:false,f_i_0:false,bg_64:"#FFFFFF",bd_paint_64:false,bdsw_amp_64:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,bd_b_0:1,bdr_tl_0:0,f_s_64:13})};window.foreui.elements.constructors.TextEditBox_srdf=function(){window.foreui.elements.TextEditBox_srdf=
new TextEditBox("TextEditBox_srdf",{f_n_64:"Arial",f_c_64:"#808080",bd_b_64:1,bgo_64:255,bd_t_64:1,bdr_br_64:0,bdt_64:"solid",bdc_64:"#C0C0C0",f_u_64:false,f_b_64:false,bd_r_0:1,bdr_tr_0:0,f_s_0:11,encrypt:false,bdr_tr_64:0,bdsw_int_0:0,margin:5,f_i_64:false,bd_r_64:1,f_b_0:false,bd_paint_0:true,bdr_br_0:0,bdr_tl_64:0,bdr_bl_64:0,bounds:{height:252,width:267,y:0,x:0},bd_t_0:1,txt_a_0:"left",bdw_64:1,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#808080",bdw_0:1,bdsw_int_64:0,f_c_0:"#000000",
multirow:true,bd_l_64:1,bg_0:"#FFFFFF",txt_a_64:"left",f_u_0:false,f_i_0:false,bg_64:"#FFFFFF",bd_paint_64:true,bdsw_amp_64:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:255,bd_b_0:1,bdr_tl_0:0,f_s_64:11})};window.foreui.elements.constructors.ScrollableContainer_1=function(){window.foreui.elements.ScrollableContainer_1=new ScrollableContainer("ScrollableContainer_1",{bdsw_amp_0:0,bg_0:"#FFFFFF",bd_l_0:1,hsc:true,bd_paint_0:true,bdt_0:"solid",bdr_br_0:0,state:0,bdc_0:"#808080",bdw_0:1,bounds:{height:568,width:326,
y:193,x:429},bdr_bl_0:0,bd_t_0:1,bdr_tr_0:0,bd_r_0:1,bgo_0:255,bd_b_0:1,bdr_tl_0:0,bdsw_int_0:0,vsc:true})};window.foreui.elements.constructors.TextEditBox_argument2=function(){window.foreui.elements.TextEditBox_argument2=new TextEditBox("TextEditBox_argument2",{f_n_64:"Arial",f_c_64:"#808080",bd_b_64:1,bgo_64:255,bd_t_64:1,bdr_br_64:0,bdt_64:"solid",bdc_64:"#C0C0C0",f_u_64:false,f_b_64:false,bd_r_0:1,bdr_tr_0:0,f_s_0:11,encrypt:false,bdr_tr_64:0,bdsw_int_0:0,margin:5,f_i_64:false,bd_r_64:1,f_b_0:false,
bd_paint_0:true,bdr_br_0:0,bdr_tl_64:0,bdr_bl_64:0,bounds:{height:151,width:267,y:0,x:0},bd_t_0:1,txt_a_0:"left",bdw_64:1,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#808080",bdw_0:1,bdsw_int_64:0,f_c_0:"#000000",multirow:true,bd_l_64:1,bg_0:"#FFFFFF",txt_a_64:"left",f_u_0:false,f_i_0:false,bg_64:"#FFFFFF",bd_paint_64:true,bdsw_amp_64:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:255,bd_b_0:1,bdr_tl_0:0,f_s_64:11})};window.foreui.elements.constructors.TextEditBox_relations=function(){window.foreui.elements.TextEditBox_relations=
new TextEditBox("TextEditBox_relations",{f_n_64:"Arial",f_c_64:"#808080",bd_b_64:1,bgo_64:255,bd_t_64:1,bdr_br_64:0,bdt_64:"solid",bdc_64:"#C0C0C0",f_u_64:false,f_b_64:false,bd_r_0:1,bdr_tr_0:0,f_s_0:11,encrypt:false,bdr_tr_64:0,bdsw_int_0:0,margin:5,f_i_64:false,bd_r_64:1,f_b_0:false,bd_paint_0:true,bdr_br_0:0,bdr_tl_64:0,bdr_bl_64:0,bounds:{height:83,width:268,y:0,x:0},bd_t_0:1,txt_a_0:"left",bdw_64:1,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#808080",bdw_0:1,bdsw_int_64:0,
f_c_0:"#000000",multirow:true,bd_l_64:1,bg_0:"#FFFFFF",txt_a_64:"left",f_u_0:false,f_i_0:false,bg_64:"#FFFFFF",bd_paint_64:true,bdsw_amp_64:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:255,bd_b_0:1,bdr_tl_0:0,f_s_64:11})};window.foreui.elements.constructors.TextEditBox_argument1=function(){window.foreui.elements.TextEditBox_argument1=new TextEditBox("TextEditBox_argument1",{f_n_64:"Arial",f_c_64:"#808080",bd_b_64:1,bgo_64:255,bd_t_64:1,bdr_br_64:0,bdt_64:"solid",bdc_64:"#C0C0C0",f_u_64:false,f_b_64:false,bd_r_0:1,
bdr_tr_0:0,f_s_0:11,encrypt:false,bdr_tr_64:0,bdsw_int_0:0,margin:5,f_i_64:false,bd_r_64:1,f_b_0:false,bd_paint_0:true,bdr_br_0:0,bdr_tl_64:0,bdr_bl_64:0,bounds:{height:50,width:268,y:0,x:0},bd_t_0:1,txt_a_0:"left",bdw_64:1,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#808080",bdw_0:1,bdsw_int_64:0,f_c_0:"#000000",multirow:true,bd_l_64:1,bg_0:"#FFFFFF",txt_a_64:"left",f_u_0:false,f_i_0:false,bg_64:"#FFFFFF",bd_paint_64:true,bdsw_amp_64:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:255,bd_b_0:1,
bdr_tl_0:0,f_s_64:11})};window.foreui.elements.constructors.TextBox_7=function(){window.foreui.elements.TextBox_7=new TextBox("TextBox_7",{f_n_64:"Arial",f_c_64:"#808080",bd_b_64:1,bgo_64:0,txt_va_64:"top",bd_t_64:1,bdr_br_64:0,bdt_64:"solid",bdc_64:"#C0C0C0",f_u_64:false,f_b_64:true,bd_r_0:1,bdr_tr_0:0,f_s_0:13,bdr_tr_64:0,bdsw_int_0:0,f_i_64:false,bd_r_64:1,f_b_0:true,bd_paint_0:false,bdr_br_0:0,bdr_tl_64:0,bdr_bl_64:0,bounds:{height:17,width:141,y:0,x:0},bd_t_0:1,txt_a_0:"left",bdw_64:1,bdsw_amp_0:0,
bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#000000",bdw_0:1,bdsw_int_64:0,f_c_0:"#000000",bd_l_64:1,txt_va_0:"top",bg_0:"#FFFFFF",txt_a_64:"left",f_u_0:false,f_i_0:false,bg_64:"#FFFFFF",bd_paint_64:false,bdsw_amp_64:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,bd_b_0:1,bdr_tl_0:0,f_s_64:13})};window.foreui.elements.constructors.TextBox_6=function(){window.foreui.elements.TextBox_6=new TextBox("TextBox_6",{f_n_64:"Arial",f_c_64:"#808080",bd_b_64:1,bgo_64:0,txt_va_64:"top",bd_t_64:1,bdr_br_64:0,bdt_64:"solid",
bdc_64:"#C0C0C0",f_u_64:false,f_b_64:true,bd_r_0:1,bdr_tr_0:0,f_s_0:13,bdr_tr_64:0,bdsw_int_0:0,f_i_64:false,bd_r_64:1,f_b_0:true,bd_paint_0:false,bdr_br_0:0,bdr_tl_64:0,bdr_bl_64:0,bounds:{height:17,width:141,y:0,x:0},bd_t_0:1,txt_a_0:"left",bdw_64:1,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#000000",bdw_0:1,bdsw_int_64:0,f_c_0:"#000000",bd_l_64:1,txt_va_0:"top",bg_0:"#FFFFFF",txt_a_64:"left",f_u_0:false,f_i_0:false,bg_64:"#FFFFFF",bd_paint_64:false,bdsw_amp_64:0,f_n_0:"Arial",
bdr_bl_0:0,bgo_0:0,bd_b_0:1,bdr_tl_0:0,f_s_64:13})};window.foreui.elements.constructors.TextBox_5=function(){window.foreui.elements.TextBox_5=new TextBox("TextBox_5",{f_n_64:"Arial",f_c_64:"#808080",bd_b_64:1,bgo_64:0,txt_va_64:"top",bd_t_64:1,bdr_br_64:0,bdt_64:"solid",bdc_64:"#C0C0C0",f_u_64:false,f_b_64:true,bd_r_0:1,bdr_tr_0:0,f_s_0:13,bdr_tr_64:0,bdsw_int_0:0,f_i_64:false,bd_r_64:1,f_b_0:true,bd_paint_0:false,bdr_br_0:0,bdr_tl_64:0,bdr_bl_64:0,bounds:{height:18,width:87,y:0,x:0},bd_t_0:1,txt_a_0:"left",
bdw_64:1,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#000000",bdw_0:1,bdsw_int_64:0,f_c_0:"#000000",bd_l_64:1,txt_va_0:"top",bg_0:"#FFFFFF",txt_a_64:"left",f_u_0:false,f_i_0:false,bg_64:"#FFFFFF",bd_paint_64:false,bdsw_amp_64:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,bd_b_0:1,bdr_tl_0:0,f_s_64:13})};window.foreui.elements.constructors.TextEditBox_text=function(){window.foreui.elements.TextEditBox_text=new TextEditBox("TextEditBox_text",{f_n_64:"Arial",f_c_64:"#808080",bd_b_64:1,bgo_64:255,
bd_t_64:1,bdr_br_64:0,bdt_64:"solid",bdc_64:"#C0C0C0",f_u_64:false,f_b_64:false,bd_r_0:1,bdr_tr_0:0,f_s_0:11,encrypt:false,bdr_tr_64:0,bdsw_int_0:0,margin:5,f_i_64:false,bd_r_64:1,f_b_0:false,bd_paint_0:true,bdr_br_0:0,bdr_tl_64:0,bdr_bl_64:0,bounds:{height:74,width:326,y:0,x:0},bd_t_0:1,txt_a_0:"left",bdw_64:1,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#808080",bdw_0:1,bdsw_int_64:0,f_c_0:"#000000",multirow:false,bd_l_64:1,bg_0:"#FFFFFF",txt_a_64:"left",f_u_0:false,f_i_0:false,
bg_64:"#FFFFFF",bd_paint_64:true,bdsw_amp_64:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:255,bd_b_0:1,bdr_tl_0:0,f_s_64:11})};window.foreui.elements.constructors.TextBox_4=function(){window.foreui.elements.TextBox_4=new TextBox("TextBox_4",{f_n_64:"Arial",f_c_64:"#808080",bd_b_64:1,bgo_64:0,txt_va_64:"top",bd_t_64:1,bdr_br_64:0,bdt_64:"solid",bdc_64:"#C0C0C0",f_u_64:false,f_b_64:true,bd_r_0:1,bdr_tr_0:0,f_s_0:13,bdr_tr_64:0,bdsw_int_0:0,f_i_64:false,bd_r_64:1,f_b_0:true,bd_paint_0:false,bdr_br_0:0,bdr_tl_64:0,
bdr_bl_64:0,bounds:{height:17,width:141,y:0,x:0},bd_t_0:1,txt_a_0:"left",bdw_64:1,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#000000",bdw_0:1,bdsw_int_64:0,f_c_0:"#000000",bd_l_64:1,txt_va_0:"top",bg_0:"#FFFFFF",txt_a_64:"left",f_u_0:false,f_i_0:false,bg_64:"#FFFFFF",bd_paint_64:false,bdsw_amp_64:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,bd_b_0:1,bdr_tl_0:0,f_s_64:13})};window.foreui.elements.constructors.GroupFrame_3=function(){window.foreui.elements.GroupFrame_3=new GroupFrame("GroupFrame_3",
{f_n_64:"Arial",f_c_64:"#000000",bd_b_64:1,bgo_64:255,bd_t_64:1,bdr_br_64:3,ints_64:"middle",bdt_64:"solid",f_u_64:false,bdc_64:"#191919",f_b_64:false,bdr_tr_0:3,bd_r_0:1,f_s_0:13,bdr_tr_64:3,bdsw_int_0:0,f_i_64:false,bd_r_64:1,align_0:"left",f_b_0:false,bd_paint_0:true,ints_0:"middle",bdr_br_0:3,bdr_tl_64:3,bdr_bl_64:3,bounds:{height:393,width:365,y:7,x:0},bd_t_0:1,titleMargin:5,align_64:"left",bdw_64:1,titleOffset:10,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#191919",bdw_0:1,
bdsw_int_64:0,title:"Argument(s) and Relation(s) Detection",f_c_0:"#000000",bd_l_64:1,bg_0:"#FFFFFF",f_i_0:false,f_u_0:false,bg_64:"#FFFFFF",bd_paint_64:true,bdsw_amp_64:0,bdr_bl_0:3,f_n_0:"Arial",bgo_0:255,bd_b_0:1,bdr_tl_0:3,f_s_64:13})};window.foreui.elements.constructors.GroupFrame_2=function(){window.foreui.elements.GroupFrame_2=new GroupFrame("GroupFrame_2",{f_n_64:"Arial",f_c_64:"#000000",bd_b_64:1,bgo_64:255,bd_t_64:1,bdr_br_64:3,ints_64:"middle",bdt_64:"solid",f_u_64:false,bdc_64:"#191919",
f_b_64:false,bdr_tr_0:3,bd_r_0:1,f_s_0:13,bdr_tr_64:3,bdsw_int_0:0,f_i_64:false,bd_r_64:1,align_0:"left",f_b_0:false,bd_paint_0:true,ints_0:"middle",bdr_br_0:3,bdr_tl_64:3,bdr_bl_64:3,bounds:{height:719,width:360,y:7,x:0},bd_t_0:1,titleMargin:5,align_64:"left",bdw_64:1,titleOffset:10,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#191919",bdw_0:1,bdsw_int_64:0,title:"Preprocessing",f_c_0:"#000000",bd_l_64:1,bg_0:"#FFFFFF",f_i_0:false,f_u_0:false,bg_64:"#FFFFFF",bd_paint_64:true,
bdsw_amp_64:0,bdr_bl_0:3,f_n_0:"Arial",bgo_0:255,bd_b_0:1,bdr_tl_0:3,f_s_64:13})};window.foreui.elements.constructors.GroupFrame_1=function(){window.foreui.elements.GroupFrame_1=new GroupFrame("GroupFrame_1",{f_n_64:"Arial",f_c_64:"#000000",bd_b_64:1,bgo_64:255,bd_t_64:1,bdr_br_64:3,ints_64:"middle",bdt_64:"solid",f_u_64:false,bdc_64:"#191919",f_b_64:false,bdr_tr_0:3,bd_r_0:1,f_s_0:13,bdr_tr_64:3,bdsw_int_0:0,f_i_64:false,bd_r_64:1,align_0:"left",f_b_0:false,bd_paint_0:true,ints_0:"middle",bdr_br_0:3,
bdr_tl_64:3,bdr_bl_64:3,bounds:{height:717,width:347,y:7,x:0},bd_t_0:1,titleMargin:5,align_64:"left",bdw_64:1,titleOffset:10,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#191919",bdw_0:1,bdsw_int_64:0,title:"Test set",f_c_0:"#000000",bd_l_64:1,bg_0:"#FFFFFF",f_i_0:false,f_u_0:false,bg_64:"#FFFFFF",bd_paint_64:true,bdsw_amp_64:0,bdr_bl_0:3,f_n_0:"Arial",bgo_0:255,bd_b_0:1,bdr_tl_0:3,f_s_64:13})};window.foreui.elements.constructors.TextBox_2=function(){window.foreui.elements.TextBox_2=
new TextBox("TextBox_2",{f_n_64:"Arial",f_c_64:"#808080",bd_b_64:1,bgo_64:0,txt_va_64:"top",bd_t_64:1,bdr_br_64:0,bdt_64:"solid",bdc_64:"#C0C0C0",f_u_64:false,f_b_64:true,bd_r_0:1,bdr_tr_0:0,f_s_0:13,bdr_tr_64:0,bdsw_int_0:0,f_i_64:false,bd_r_64:1,f_b_0:true,bd_paint_0:false,bdr_br_0:0,bdr_tl_64:0,bdr_bl_64:0,bounds:{height:14,width:55,y:0,x:0},bd_t_0:1,txt_a_0:"left",bdw_64:1,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#000000",bdw_0:1,bdsw_int_64:0,f_c_0:"#000000",bd_l_64:1,
txt_va_0:"top",bg_0:"#FFFFFF",txt_a_64:"left",f_u_0:false,f_i_0:false,bg_64:"#FFFFFF",bd_paint_64:false,bdsw_amp_64:0,f_n_0:"Arial",bdr_bl_0:0,bgo_0:0,bd_b_0:1,bdr_tl_0:0,f_s_64:13})};window.foreui.elements.constructors.GroupFrame_4=function(){window.foreui.elements.GroupFrame_4=new GroupFrame("GroupFrame_4",{f_n_64:"Arial",f_c_64:"#000000",bd_b_64:1,bgo_64:255,bd_t_64:1,bdr_br_64:3,ints_64:"middle",bdt_64:"solid",f_u_64:false,bdc_64:"#191919",f_b_64:false,bdr_tr_0:3,bd_r_0:1,f_s_0:13,bdr_tr_64:3,
bdsw_int_0:0,f_i_64:false,bd_r_64:1,align_0:"left",f_b_0:false,bd_paint_0:true,ints_0:"middle",bdr_br_0:3,bdr_tl_64:3,bdr_bl_64:3,bounds:{height:301,width:365,y:7,x:0},bd_t_0:1,titleMargin:5,align_64:"left",bdw_64:1,titleOffset:10,bdsw_amp_0:0,bd_l_0:1,bdt_0:"solid",state:0,states:[0,64],bdc_0:"#191919",bdw_0:1,bdsw_int_64:0,title:"SRDF",f_c_0:"#000000",bd_l_64:1,bg_0:"#FFFFFF",f_i_0:false,f_u_0:false,bg_64:"#FFFFFF",bd_paint_64:true,bdsw_amp_64:0,bdr_bl_0:3,f_n_0:"Arial",bgo_0:255,bd_b_0:1,bdr_tl_0:3,
f_s_64:13})};window.foreui.snapshot=[];for(var a=$(".page"),b=a.size(),d=0,c=0;c<b;c++){var e=[];window.foreui.snapshot.push(e);for(var f=a.eq(c).find(".elem"),g=f.size(),i=0;i<g;i++)e.push(f.eq(i).attr("id")),d++}var l=0,j=0,m=0;if(window.foreui.lazy){jQuery.idleTimer(500,document,{startImmediately:!0,idle:!1,enabled:!0,events:"keydown mousedown touchstart"});var k=!0,n=function(){if(j<b){var a=window.foreui.snapshot[j];if(m<a.length){getForeUIElementById(a[m++]);l++;window.status="Loaded Page: "+
(j+1)+"/"+b+", Element: "+l+"/"+d}else{j++;m=0}}if(l==d){jQuery.idleTimer("destroy");window.foreui.lazy=false}else k&&setTimeout(n,0)};$(document).bind("idle.idleTimer",function(){k=true;n()});$(document).bind("active.idleTimer",function(){k=false})}else setTimeout(function(){for(j=0;j<b;j++){var a=window.foreui.snapshot[j];for(m=0;m<a.length;m++){getForeUIElementById(a[m]);l++;window.status="Loaded Page: "+(j+1)+"/"+b+", Element: "+l+"/"+d}}},0);for(c=1;c<=b;c++)initBehaviorForId("Page_"+c);("ontouchstart"in
window||"onmsgesturechange"in window)&&convertTouchEvents()});
var convertTouchEvents=function(){var a=function(a,d,c){var e=a.changedTouches[0],f=document.createEvent("MouseEvent");f.initMouseEvent(d,!0,!0,window,1,e.screenX,e.screenY,e.clientX,e.clientY,!1,!1,!1,!1,0,null);e.target.dispatchEvent(f);c&&a.preventDefault()};document.addEventListener("touchstart",function(b){a(b,"mousedown")},!0);document.addEventListener("touchmove",function(b){a(b,"mousemove",!0)},!0);document.addEventListener("touchend",function(b){a(b,"mouseup")},!0)},preloadAllImages=function(){preloadImage("images/RadioButton_Icon__Disabled.png");
preloadImage("images/RadioButton_Icon__Hovering.png");preloadImage("images/RadioButton_Icon__Normal.png");preloadImage("images/RadioButton_Icon__Selected.png");preloadImage("images/RadioButton_Icon__Selected_Disabled.png");preloadImage("images/RadioButton_Icon__Selected_Hovering.png")};
$(window).load(function(){setTimeout(function(){$(".page").css("visibility","visible").css("visibility","hidden");$("body").css("cursor","default");for(var a=1;isPageExcluded(a);)a+=1;goToPage(a,function(){initToolbar({pin:!0,alignButton:!0,hasToolbar:!0,pageTree:{excluded:!1,children:[{title:"Page1",index:0,excluded:!1,children:[],type:"page"}],type:"root"},propertyButton:!0,dockTo:"bottom",pageButton:!0})});$(document).keydown(function(a){window.foreui.cache.keyCode=a.which;window.foreui.cache.ctrlState=
a.ctrlKey?1:0;window.foreui.cache.altState=a.altKey?1:0;window.foreui.cache.shiftState=a.shiftKey?1:0}).keyup(function(a){window.foreui.cache.keyCode=-1;window.foreui.cache.ctrlState=a.ctrlKey?1:0;window.foreui.cache.altState=a.altKey?1:0;window.foreui.cache.shiftState=a.shiftKey?1:0;33==a.which?previousPage():34==a.which&&nextPage()})},0)});var List=function(a,b){this._id=a;this._params=b;this._obj=$("#"+a);this.init()};
List.prototype={init:function(){var a=this._params,b=this._obj.children();this._obj.empty();this._bg=$('<div class="bg"></div>').appendTo(this._obj);this._bd=$('<div class="bd"></div>').appendTo(this._obj);this._fg=$('<div class="fg"></div>').appendTo(this._obj);var d=a.rowh,c=a.gap,e=a.icons,f=a.txtm,g=$('<table style="position:absolute;" cellspacing="0" cellpadding="0"></table>').appendTo(this._fg);b.children("li").each(function(a){a=createLabelObject(e[a],0,c,$(this).html());a=$('<td valign="middle" class="listCell"></td>').append(a).height(d);
$('<tr class="listRow"></tr>').append(a).appendTo(g).children().css({"padding-left":f+"px",cursor:"default"})});this.setupBehavior(this._obj);initReferences(this);var i=this;setTimeout(function(){setState(i,i._params.state,!0)},0)},updateUI:function(a){var b=this._params,d=b.state,c=a.children(".bg"),e=a.children(".bd"),f=a.children(".fg"),g=a.width(),i=a.height(),l=b["bdw_"+d],f=f.children("table");f.css({left:l+"px",top:l+"px",width:g-2*l+"px",height:i-2*l+"px"});var j=b["pbdr_"+d],m=b["horl_"+
d];e.css("border-width","0px").width(a.width()).height(a.height());j||(b["bdt_"+d]="none");a=b.bg;b.bg="transparent";generateBackgroundAndBorders(d,"",c,e,b);b.bg=a;var j=b.rows,k=b.rowh,n=Math.ceil(i/k),o=Math.max(0,n-j),q=k-i+(o-1)*k-l,a=f.children();a.children(".paddingRow").remove();for(var p=0;p<o;p++)a.append($('<tr class="listRow paddingRow"><td class="listCell"></td></tr>').height(p==o-1?q:k));c.children("table").remove();var h=f.clone().appendTo(c).find(".listCell").css("padding-left","0px").width("100%").html("");
e.children("table").remove();var c=$.browser.opera||$.browser.mozilla&&j*k<i?k:k-l,u=f.clone().appendTo(e).find(".listCell").css("height",c+"px").width("100%").html(""),t=b.txtm,s=b.selr,v=b.gap,w=b.icons;a.children(".listRow").each(function(a){var c=$(this),e=c.children(),f=$(h.get(a)),j=$(u.get(a)),k=a==n-1,i="row";1==a%2&&(i="alt");a==s&&(i="sel");generateBackgroundAndBorders(d,i,f,j,b);c.hasClass("paddingRow")||(applyFontParameters(d,i,e,b),c=getTextSize(e.text(),b["rowf_n_"+d],b["rowf_s_"+d]).width,
w[a]&&(c+=v+e.find(".icon").width()),e.css("padding-left","0px"),a=Math.max(0,Math.min(t,(g-c)/2)),e.css("padding-left",a+"px"));m&&!k&&j.css({"border-bottom-style":"solid","border-bottom-color":b[i+"bdc_"+d],"border-bottom-width":l+"px"})})},setupBehavior:function(a){var b=this,d=a.children(".fg").children("table").children().children(".listRow");d.click(function(){0==(b._params.state&64)&&b.setSelectedIndex(d.index(this)+1)})},getSelectedIndex:function(){return this._params.selr+1},setSelectedIndex:function(a){var b=
this._params;b.selr!=a-1&&(b.selr=a-1,updateElementAndReferences(this),$("#"+this._id).trigger("Selection_Changed"))},getSelectedText:function(){var a=this._params.selr;if(-1==a)return"";a=this._fg.children("table").children().children(".listRow").eq(a).children(".listCell").children(".label");return textFromView(a.text())}};var ProgressBar=function(a,b){this._id=a;this._params=b;this._obj=$("#"+a);this.init()};
ProgressBar.prototype={init:function(){this._bg=$('<div class="bg"></div>').appendTo(this._obj);this._bd=$('<div class="bd"></div>').appendTo(this._obj);this._fg=$('<div class="fg"></div>').appendTo(this._obj);this.setupBehavior(this._obj);initReferences(this);var a=this;setTimeout(function(){updateElementAndReferences(a)},0)},updateUI:function(a){var b=this._params,d=a.children(".bg"),c=a.children(".bd"),e=a.children(".fg"),f=a.width(),g=a.height();c.css("border-width","0px").width(f).height(g);
generateBackgroundAndBorders(0,"",d,c,b);var a=b.indc,d=b.indi,i=b.indw,l=b.indm,j=f*b.cur/(b.max-b.min);if(b.tile){var m=$("<div></div>").css({position:"absolute",left:l+"px",top:l+"px",width:j-2*l+"px",height:g-2*l+"px",overflow:"hidden","white-space":"nowrap"}).appendTo(e.empty());if(null!=d){var k=new Image;k.onload=function(){for(var a=this.width,b=g-2*l,c=l;c<f;c+=a)$('<img src="'+k.src+'" width="'+a+'" height="'+b+'">').appendTo(m)};k.src="images/"+d}else null!=a&&(0==a.indexOf("#")?m.css("background-color",
a):m.empty().append($('<img src="images/'+a+'" width="'+m.width()+'" height="100%" />')))}else if(0<i){var n=Math.max(j-i/2,l),o=Math.min(j+i/2,f-1-l),m=$("<div></div>").css({position:"absolute",left:n+"px",top:l+"px",width:o-n+1+"px",height:g-2*l+"px",overflow:"hidden","white-space":"nowrap"}).appendTo(e.empty());null!=d?(k=new Image,k.onload=function(){for(var a=this.width,b=g-2*l,c=i>f?a*j/f-a:0,d=n;d<o+a;d+=a)$('<img src="'+k.src+'" width="'+a+'" height="'+b+'">').css({position:"relative",left:c+
"px"}).appendTo(m)},k.src="images/"+d):null!=a&&(0==a.indexOf("#")?m.css("background-color",a):m.empty().append($('<img src="images/'+a+'" width="'+i+'" height="100%" />')))}},setupBehavior:function(){clearInterval(this.interval);var a=this,b=this._params;b.indt&&(this.interval=setInterval(function(){var d=b.cur+b.step;d>b.max&&(d=b.min);a.setCurrentValue(d)},300))},setCurrentValue:function(a){var b=this._params;a>b.max?a=b.max:a<b.min&&(a=b.min);b.cur!=a&&(b.cur=a,updateElementAndReferences(this),
$("#"+this._id).trigger("Value_Changed"))},getCurrentValue:function(){return this._params.cur},getMaxValue:function(){return this._params.max}};window.foreui||(window.foreui={});
window.foreui.sys_properties={SCREEN_WIDTH:getScreenWidth,SCREEN_HEIGHT:getScreenHeight,CURRENT_PAGE_INDEX:getCurrentPageIndex,CURRENT_PAGE_TITLE:getCurrentPageTitle,AVAILABLE_PAGE_INDICES:getAvailablePageIndices,AVAILABLE_PAGE_TITLES:getAvailablePageTitles,CURRENT_YEAR:getCurrentYear,CURRENT_MONTH:getCurrentMonth,CURRENT_DAY:getCurrentDay,CURRENT_HOURS:getCurrentHours,CURRENT_MINUTES:getCurrentMinutes,CURRENT_SECONDS:getCurrentSeconds,CURRENT_TIMESTAMP:getCurrentTimestamp,CURRENT_KEY_CODE:getCurrentKeyCode,
CTRL_KEY_STATE:getCtrlKeyState,ALT_KEY_STATE:getAltKeyState,SHIFT_KEY_STATE:getShiftKeyState,FOCUSED_ELEMENT_ID:getFocusedElementId,CURRENT_CURSOR_X:getCurrentCursorX,CURRENT_CURSOR_Y:getCurrentCursorY,CURRENT_EVENT:getCurrentEvent};window.foreui.properties={};var RadioButton=function(a,b){this._id=a;this._params=b;this._obj=$("#"+a);this.init()};
RadioButton.prototype={init:function(){var a=this._params;this._obj.empty();this._bg=$('<div class="bg"></div>').appendTo(this._obj);this._bd=$('<div class="bd"></div>').appendTo(this._obj);a=createLabelObject(a["icon_"+a.state],a.icon_p,a["gap_"+a.state],a.text,!0);this._fg=$('<div class="fg vcenter_outter"><div class="vcenter_middle"><div class="vcenter_inner">'+a.html()+"</div></div></div>").appendTo(this._obj);this.setupBehavior(this._obj);initReferences(this);var b=this;setTimeout(function(){setState(b,
b._params.state,!0)},0)},updateUI:function(a){var b=this._params,d=b.state,c=a.children(".bg"),e=a.children(".bd"),f=a.children(".fg"),g=a.width(),a=a.height();e.css("border-width","0px").width(g).height(a);generateBackgroundAndBorders(d,"",c,e,b);f.find(".icon").attr("src","images/"+b["icon_"+b.state]);f.width(g).height(a).css({cursor:64==d||96==d?"default":"pointer"});applyFontParameters(d,"",f.find(".vcenter_middle"),b)},setupBehavior:function(a){var b=this._params,d=this;a.mouseenter(function(){setState(d,
b.state&32?48:16)}).mouseleave(function(){setState(d,b.state&32?32:0)}).mousedown(function(){setState(d,48)})},getSelected:function(){return 0<(this._params.state&32)},selectRadioButton:function(a,b,d){for(var d=d?findSiblingsInGroup(a,!1):[],c=0;c<a.length;c++){var e=getForeUIElementById(a[c]);if(e){var f=e._params.state&32?!1:!0;0==b?f=!1:1==b&&(f=!0);f?setState(e,e._params.state|32):setState(e,e._params.state&223)}}for(c=0;c<d.length;c++)(e=getForeUIElementById(d[c]))&&setState(e,e._params.state&
223)},onSelected:function(){$("#"+this._id).trigger("Selected")},onUnselected:function(){$("#"+this._id).trigger("Unselected")}};var ScrollableContainer=function(a,b){this._id=a;this._params=b;this._obj=$("#"+a);this.init()};
ScrollableContainer.prototype={init:function(){var a=this._params,b=this._obj.children();this._obj.empty();this._bg=$('<div class="bg"></div>').appendTo(this._obj);this._bd=$('<div class="bd"></div>').appendTo(this._obj);this._fg=$('<div class="fg scrollable"></div>').append(b).css({"overflow-x":a.hsc?"scroll":"hidden","overflow-y":a.vsc?"scroll":"hidden"}).appendTo(this._obj);initReferences(this);var d=this;setTimeout(function(){updateElementAndReferences(d)},0)},updateUI:function(a){var b=this._params,
d=a.children(".bg"),c=a.children(".bd"),e=a.children(".fg"),f=a.width(),a=a.height();c.css("border-width","0px").width(f).height(a);generateBackgroundAndBorders(0,"",d,c,b);b=b.bdw_0;e.css({left:b+"px",top:b+"px",width:f-2*b+"px",height:a-2*b+"px"})}};var TextBox=function(a,b){this._id=a;this._params=b;this._obj=$("#"+a);this.init()};
TextBox.prototype={init:function(){var a=this._params;this._text=this._obj.html();this._obj.empty();this._bg=$('<div class="bg"></div>').appendTo(this._obj);this._bd=$('<div class="bd"></div>').appendTo(this._obj);this._fg=$('<div class="fg"><table cellspacing="0" cellpadding="0"><tr><td>'+htmlToView(this._text)+"</td></tr></table></div>").appendTo(this._obj);var b=a.bd_paint_0?a.bdw_0:0,d=a["txt_a_"+a.state],a=a["txt_va_"+a.state];this._fg.find("td").css({"text-align":d,"vertical-align":a,padding:b+
"px"});initReferences(this);var c=this;setTimeout(function(){setState(c,c._params.state,!0)},0)},updateUI:function(a){var b=this._params,d=b.state,c=a.children(".bg"),e=a.children(".bd"),f=a.children(".fg"),g=a.width(),a=a.height();e.css("border-width","0px").width(g).height(a);generateBackgroundAndBorders(d,"",c,e,b);c=b["bdw_"+d];c=b["bd_paint_"+d]?c:0;f.find("table").width(g-2*c).height(a-2*c);applyFontParameters(d,"",f.find("td").html(htmlToView(this._text)),b)},getText:function(){return textFromView(this._text)},
setText:function(a){this._text=a},setBgColor:function(a){var b=this._params;b.bg_0=b.bg_64=a;updateElementAndReferences(this)},setBgOpacity:function(a){var b=this._params;b.bgo_0=b.bgo_64=255*a/100;updateElementAndReferences(this)},setTextColor:function(a){var b=this._params;b.f_c_0=b.f_c_64=a;updateElementAndReferences(this)},getTextLength:function(){return this.getText().length}};var TextEditBox=function(a,b){this._id=a;this._params=b;this._obj=$("#"+a);this.init()};
TextEditBox.prototype={init:function(){var a=this._params;this._text=this._obj.html().replace(/\t/g,"");this._obj.empty();this._bg=$('<div class="bg"></div>').appendTo(this._obj);this._bd=$('<div class="bd"></div>').appendTo(this._obj);this._fg=$('<div class="fg"></div>').appendTo(this._obj);var b=a["txt_a_"+a.state],d=a.margin;$(a.multirow?'<textarea class="edit">'+this._text+"</textarea>":'<input class="edit" type="'+(a.encrypt?"password":"text")+'" value="'+this._text+'" />').css({width:"100%",
height:"100%","text-align":b,"padding-left":d,"padding-right":d,"background-color":"transparent","border-width":"0px",overflow:"hidden"}).appendTo(this._fg);this.setupBehavior(this._obj);initReferences(this);var c=this;setTimeout(function(){setState(c,c._params.state,!0)},0)},updateUI:function(a){var b=this._params,d=b.state,c=a.children(".bg"),e=a.children(".bd"),f=a.children(".fg"),g=a.width(),a=a.height();e.css("border-width","0px").width(g).height(a);generateBackgroundAndBorders(d,"",c,e,b);c=
b.margin;f.find(".edit").width(g-2*c).height(a).val(this._text).prop("disabled",0<(d&64));applyFontParameters(d,"",f.find(".edit"),b)},setupBehavior:function(a){var b=this;a.children(".fg").find(".edit").change(function(){b._text=$(this).val();$("#"+b._id).trigger("Value_Changed");updateElementAndReferences(b)}).focus(function(){window.foreui.focusedElementId=b._id;onPropertyValueChanged("FOCUSED_ELEMENT_ID",b._id)})},getValue:function(){return this._obj.children(".fg").find(".edit").val()},setCurrentValue:function(a){this.getValue()!=
a&&(this._text=a,this._obj.children(".fg").find(".edit").val(a),$("#"+this._id).trigger("Value_Changed"),updateElementAndReferences(this))},setFocus:function(){var a=this._obj.children(".fg").find(".edit").get(0);a.focus();a.select();window.foreui.focusedElementId=this._id;onPropertyValueChanged("FOCUSED_ELEMENT_ID",this._id)},getTextLength:function(){return this.getValue().length}};
ForeUIToolbar.prototype={_init:function(){var a=this._conf,b=$("body");this._toolbar=$('<div class="toolbar"></div>').appendTo(b);this._controls=$('<div class="controls" style="white-space:nowrap;"></div>').appendTo(this._toolbar);this._controls.append('<img src="styles/foreui_logo.gif" align="absmiddle" />');this._controls.append('<span style="width:10px;"></span>');this._pageLabel=$("<span>Page:</span>").appendTo(this._controls);this._prevButton=$('<span class="button" title="Go to previous page (Page Up)" style="width:14px">&lt;</span>').appendTo(this._controls);
this._pageIndicator=$('<span class="pageIndicator">1/1</span>').appendTo(this._controls);this._nextButton=$('<span class="button" title="Go to next page (Page Down)" style="width:14px">&gt;</span>').appendTo(this._controls);var d=0.8*document.body.clientHeight;this._gotoButton=$('<span class="button" title="Choose a page from the list">Goto...</span>').appendTo(this._controls);this._pageList=$('<div class="pageList winFrame"><div class="winTitle"><div class="winTitleClose">X</div>Pages:</div><div class="winClient"><ul></ul></div></div>').appendTo(b);
for(var c=this._pageList.children().children("ul"),e=a.pageTree.children,f=0;f<e.length;f++)this._appendPgTreeNode(e[f],c);this._pageList.width(Math.min(400,Math.max(200,this._pageList.width()+20)));this._pageList.height(Math.min(d,Math.max(200,this._pageList.height()+20)));this._controls.append('<span style="width:10px;"></span>');this._propertyButton=$('<span class="button" title="View Properties">Properties</span>').appendTo(this._controls);this._propertyList=$('<div class="propertyList winFrame"><div class="winTitle"><div class="winTitleClose">X</div>Properties:</div><div class="winClient"><table border="1" cellspacing="0" cellpadding="5"></table></div></div>').appendTo(b);
b=this._propertyList.children().children("table");e=window.foreui.sys_properties;for(propName in e)c=$("<tr></tr>").appendTo(b),$('<td style="font-weight:bold;"></td>').append(propName).appendTo(c),$('<td style="font-weight:bold;" width="50%" class="'+propName+'">'+toJsonString(getPropertyValue(propName))+"</td>").appendTo(c);e=window.foreui.properties;for(propName in e)c=$("<tr></tr>").appendTo(b),$("<td></td>").append(propName).appendTo(c),$('<td width="50%" class="'+propName+'">'+toJsonString(getPropertyValue(propName))+
"</td>").appendTo(c);this._propertyList.width(Math.min(400,Math.max(300,this._propertyList.width())));this._propertyList.height(Math.min(d,Math.max(300,this._propertyList.height())));this._schedulePropertyUpdate(b);this._controls.append('<span style="width:10px;"></span>');this._alignButton=$('<span class="button" title="Click to Change Content Alignment">Content Align: '+window.foreui.align+"</span>").appendTo(this._controls);this._pinButton=$('<img class="pinButton" src="styles/'+(a.pin?"pin.gif":
"unpin.gif")+'" title="Click to pin/unpin the toolbar" style="position:absolute;cursor:pointer;">').appendTo(this._toolbar);this._dockButtons=$('<div class="dockButtons"></div>').appendTo(this._toolbar);this._dockTop=$('<div class="dockButton dockTop" title="Dock to top">').appendTo(this._dockButtons);this._dockLeft=$('<div class="dockButton dockLeft" title="Dock to left">').appendTo(this._dockButtons);this._dockBottom=$('<div class="dockButton dockBottom" title="Dock to bottom">').appendTo(this._dockButtons);
this._dockRight=$('<div class="dockButton dockRight" title="Dock to right">').appendTo(this._dockButtons);this["_dock"+a.dockTo.charAt(0).toUpperCase()+a.dockTo.substr(1)].addClass("hlDockButton");this._setupBehavior();var g=this;setTimeout(function(){g._updateLayout();g._toolbar.trigger("mouseout")},50)},_appendPgTreeNode:function(a,b){var d=a.children,c=parseInt(a.index)+1,e=$("<li></li>").attr({type:a.type,excluded:a.excluded}).appendTo(b);"page"==a.type&&e.attr("pageIndex",c);$(a.excluded||"folder"==
a.type?"<span></span>":'<a href="javascript:goToPage('+c+');"></a>').append(a.title).appendTo(e).children("img");"folder"==a.type?e.css("list-style",'url("styles/'+(a.excluded?"folder_excluded.png":"folder.png")+'")'):e.css("list-style",'url("styles/'+(a.excluded?"page_excluded.png":"page.png")+'")');a.excluded&&e.children("span").addClass("excluded");if(0<d.length){c=$("<ul></ul>").appendTo(e);for(e=0;e<d.length;e++)this._appendPgTreeNode(d[e],c)}},_updateLayout:function(a){var b=this._conf,d=this._controls,
c,e,f,g,i,l,j,m,k;switch(b.dockTo){case "top":case "bottom":c="left "+b.dockTo;e="100%";f="30px";g='url("styles/toolbar_hor.png") repeat-x';i="right center";l="-5 0";j="right center";m="left center";k="-10 0";d.removeClass("rotate90Degrees");break;case "left":case "right":c=b.dockTo+" top",e="30px",f="100%",g='url("styles/toolbar_vert.png") repeat-y',i="center bottom",l="0 -5",j="center bottom",m="center top",k="0 -10",d.addClass("rotate90Degrees")}this._toolbar.css({width:e,height:f,background:g,
margin:"0px"}).position({my:c,at:c,of:window});this._pinButton.position({my:i,at:i,of:this._toolbar,offset:l});this._dockButtons.position({my:j,at:m,of:this._pinButton,offset:k});a&&this._updateLayout(!1)},_setupBehavior:function(){var a=this._conf,b=this;a.pageButton||this._pageLabel.add(this._prevButton).add(this._pageIndicator).add(this._nextButton).add(this._gotoButton).hide();a.propertyButton||this._propertyButton.hide();a.alignButton||this._alignButton.hide();$(window).bind("scroll resize",
function(){b._updateLayout();b._toolbar.trigger("mouseout")});this._pinButton.click(function(){a.pin=!a.pin;b._pinButton.attr("src","styles/"+(a.pin?"pin.gif":"unpin.gif"))});var d;this._toolbar.mouseover(function(){d&&(clearTimeout(d),d=void 0);b._toolbar.css("margin","0px");b._controls.css("visibility","inherit");switch(a.dockTo){case "bottom":b._toolbar.css("height","30px");break;case "right":b._toolbar.css("width","30px")}}).mouseout(function(){a.pin||(d&&clearTimeout(d),d=setTimeout(function(){switch(a.dockTo){case "top":b._toolbar.animate({marginTop:"-28px"},
1E3);break;case "bottom":b._toolbar.animate({marginTop:"28px",height:"2px"},1E3);break;case "left":b._toolbar.animate({marginLeft:"-28px"},1E3);break;case "right":b._toolbar.animate({marginLeft:"28px",width:"2px"},1E3,function(){b._controls.css("visibility","hidden")})}},2E3))});var c=this._dockButtons.children(".dockButton");c.click(function(){c.removeClass("hlDockButton");$(this).addClass("hlDockButton")});this._dockTop.click(function(){a.dockTo="top";b._updateLayout(!0)});this._dockLeft.click(function(){a.dockTo=
"left";b._updateLayout(!0)});this._dockBottom.click(function(){a.dockTo="bottom";b._updateLayout(!0)});this._dockRight.click(function(){a.dockTo="right";b._updateLayout(!0)});this._prevButton.click(function(){previousPage()});this._nextButton.click(function(){nextPage()});this._gotoButton.click(function(){b._propertyList.is(":visible")&&b._toggleWindow(b._propertyList,b._propertyButton);b._toggleWindow(b._pageList,b._gotoButton);b._updateLayout()});this._propertyButton.click(function(){b._pageList.is(":visible")&&
b._toggleWindow(b._pageList,b._propertyButton);b._toggleWindow(b._propertyList,b._propertyButton);b._updateLayout()});this._alignButton.click(function(){window.foreui.align="left"==window.foreui.align?"center":"center"==window.foreui.align?"right":"left";$(this).html("Content Align: "+window.foreui.align);$(".page").position({my:window.foreui.align+" top",at:window.foreui.align+" top",of:document}).css("top","0px")});$("body").children(".winFrame").resizable({handles:"all",minWidth:100,minHeight:30}).draggable({handle:".winTitle"}).resize(function(){var a=
$(this);a.children(".winClient").width(a.width()).height(a.height()-30)}).children(".winTitle").children(".winTitleClose").click(function(){$(this).closest(".winFrame").css({visibility:"hidden",display:"none"})})},_toggleWindow:function(a,b){var d=this._conf;a.css("display","hidden"==a.css("visibility")?"block":"none");a.css("visibility","hidden"==a.css("visibility")?"inherit":"hidden");var c=0.8*document.body.clientHeight;a.width(Math.min(400,Math.max(200,a.width()+20)));a.height(Math.min(c,Math.max(200,
a.height()+20)));a.trigger("resize");switch(d.dockTo){case "top":a.position({my:"left top",at:"left bottom",of:b?b:this._toolbar});break;case "bottom":a.position({my:"left bottom",at:"left top",of:b?b:this._toolbar});break;case "left":a.position({my:"left center",at:"right center",of:this._toolbar});break;case "right":a.position({my:"right center",at:"left center",of:this._toolbar})}},_schedulePropertyUpdate:function(a){setInterval(function(){a.is(":visible")&&(a.find(".CURRENT_YEAR").html(getPropertyValue("CURRENT_YEAR")),
a.find(".CURRENT_MONTH").html(getPropertyValue("CURRENT_MONTH")),a.find(".CURRENT_DAY").html(getPropertyValue("CURRENT_DAY")),a.find(".CURRENT_HOURS").html(getPropertyValue("CURRENT_HOURS")),a.find(".CURRENT_MINUTES").html(getPropertyValue("CURRENT_MINUTES")),a.find(".CURRENT_SECONDS").html(getPropertyValue("CURRENT_SECONDS")),a.find(".CURRENT_TIMESTAMP").html(getPropertyValue("CURRENT_TIMESTAMP")))},1E3);$(window).resize(function(){a.find(".SCREEN_WIDTH").html(getScreenWidth());a.find(".SCREEN_HEIGHT").html(getScreenHeight())});
$(document).mousemove(function(b){a.find(".CURRENT_CURSOR_X").html(b.pageX);a.find(".CURRENT_CURSOR_Y").html(b.pageY)}).bind("keydown",function(){a.find(".CURRENT_KEY_CODE").html(getCurrentKeyCode());a.find(".CTRL_KEY_STATE").html(getCtrlKeyState());a.find(".ALT_KEY_STATE").html(getAltKeyState());a.find(".SHIFT_KEY_STATE").html(getShiftKeyState())}).keyup(function(){a.find(".CURRENT_KEY_CODE").html("-1");a.find(".CTRL_KEY_STATE").html(getCtrlKeyState());a.find(".ALT_KEY_STATE").html(getAltKeyState());
a.find(".SHIFT_KEY_STATE").html(getShiftKeyState())})},onPropertyChanged:function(a,b){var d=$("body").children(".propertyList").find("table");if(0<d.size()){var c=d.find("."+a);0<c.size()?c.html(toJsonString(b)):(d=$("<tr></tr>").appendTo(d),$("<td></td>").append(a).appendTo(d),$('<td width="50%" class="'+a+'">'+toJsonString(b)+"</td>").appendTo(d))}},updatePageIndicator:function(a,b){$("body").children(".toolbar").find(".pageIndicator").html(a+"/"+b)},updateSelectedPage:function(a){var b=$("body").children(".pageList");
b.find("li[type='page'][excluded='false']").css("list-style",'url("styles/page.png")');b.find("li[pageIndex='"+a+"']").css("list-style",'url("styles/page_selected.png")')}};